---
sidebar: sidebar 
permalink: reference_requirements_vcp.html 
summary: vCenter Server용 NetApp Element 플러그인을 사용하기 전에 제품 설치 및 사용을 위한 사전 요구 사항을 이해해야 합니다. 
keywords: netapp, hci, kubernetes, on premise, cloud services 
---
= vCenter Server용 Element 플러그인의 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
vCenter Server용 NetApp Element 플러그인을 사용하여 NetApp HCI 또는 SolidFire All-Flash 어레이 스토리지를 관리하려면 먼저 시스템이 플러그인 사용 요구사항을 충족하는지 확인해야 합니다.



== VMware vSphere 사전 요구 사항

vCenter Server용 NetApp Element 플러그인을 사용하려면 소프트웨어 iSCSI 어댑터와 iSCSI 네트워킹이 구성된 vCenter 및 ESXi를 포함한 VMware vSphere 7.0, 6.7 또는 6.5가 필요합니다.



=== 플러그인에서 지원하는 VMware vSphere 버전

플러그인은 다음과 같은 주요 버전의 VMware 소프트웨어를 지원합니다.

* vSphere 7.0 및 7.0 업데이트 1 - vCenter Server, ESXi, VMFS5 및 VMFS6 데이터 저장소 포함
+

IMPORTANT: VMware vCenter Server 7.0 U3으로 업그레이드하면 vCenter Server용 NetApp Element 플러그인의 모든 버전이 배포되지 않습니다. 이 문제를 해결하려면 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/vCenter_plug-in_deployment_fails_after_upgrading_vCenter_to_version_7.0_U3["이 KB 문서를 참조하십시오"^].

* vCenter Server, ESXi, VMFS5 및 VMFS6 데이터 저장소를 포함한 vSphere 6.7 및 6.7 업데이트 1 및 3
+

IMPORTANT: 플러그인은 HTML5 vSphere Web Client의 버전 6.7 U2 빌드 13007421 및 업데이트 2a 이전에 릴리스된 기타 6.7 U2 빌드(빌드 13643870)와 호환되지 않습니다. Flash/Flex용 버전 6.7 U2 vSphere Web Client와 호환됩니다.

* vCenter Server, ESXi, VMFS5 및 VMFS6 데이터 저장소를 포함한 vSphere 6.5
+

IMPORTANT: 이 플러그인은 VMware vCenter Server 4.6, 4.7 및 4.8용 Element Plug-in용 버전 6.5와 호환되지 않습니다.





=== vSphere 6.0 지원이 종료됩니다


IMPORTANT: VMware vSphere 6.0은 2020년 3월 12일에 지원 종료 상태에 도달했습니다. NetApp HCI 1.8 및 Element 12부터는 vSphere 6.0이 더 이상 지원되지 않습니다. 자세한 내용은 다음을 참조하십시오 https://mysupport.netapp.com/info/communications/ECMLP2863840.html["제품 공산품"].



== vSphere 호환성 및 Best Practice

플러그인을 사용하기 전에 다음 기능과 권장 사항을 고려하십시오.

* vCenter 고가용성(VCHA)은 지원되지 않습니다.
* 선택한 ESXi 호스트에서 지원하는 가장 높은 VMFS 버전을 사용하여 데이터 저장소를 생성하므로 VMFS 호환성 문제를 방지하려면 모든 클러스터 구성원이 동일한 버전의 vSphere 및 ESXi를 실행해야 합니다.
* vSphere HTML5 Web Client 및 Flash Web Client에는 결합할 수 없는 별도의 데이터베이스가 있습니다. 한 클라이언트에 추가된 클러스터는 다른 클라이언트에서는 표시되지 않습니다. 두 클라이언트를 모두 사용하려면 둘 다에 클러스터를 추가합니다.




== NetApp Element 지원

플러그인은 다음과 같은 주요 버전을 지원합니다.

* Element 12.x, SolidFire 엔터프라이즈 SDS 포함
* 요소 11.x




== 네트워크 포트 요구 사항

시스템을 원격으로 관리하고 데이터 센터 외부의 클라이언트가 리소스에 연결할 수 있도록 데이터 센터의 에지 방화벽을 통해 일부 TCP 포트를 허용해야 합니다. NetApp HCI 및 SolidFire 시스템에서 사용되는 포트의 전체 목록은 다음을 참조하십시오 link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html["페이지"].

[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 문서"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]

