---
sidebar: sidebar 
permalink: vcp_task_create_manage_user_accounts.html 
summary: 플러그인을 사용하여 사용자 계정을 만들고 관리할 수 있습니다. 
keywords: netapp, storage, accounts, vcp, vcenter, element 
---
= 사용자 계정을 만들고 관리합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:vcp_concept_accounts.html["사용자 계정"^] NetApp Element 소프트웨어 기반 네트워크에서 스토리지 리소스에 대한 액세스를 제어하는 데 사용됩니다.

.옵션
*  an account
*  an account
*  an account




== 계정을 만듭니다

고유한 사용자 계정을 생성하여 스토리지 볼륨에 대한 액세스를 허용할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 하나 이상의 클러스터를 추가하고 실행해야 합니다.


.단계
. NetApp Element 관리 > 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Accounts * 하위 탭을 선택합니다.
. 계정 만들기 * 를 선택합니다.
. 사용자 이름을 입력합니다.
+

TIP: 이름 지정 모범 사례를 설명합니다. 이 기능은 사용자 환경에서 여러 클러스터 또는 vCenter Server를 사용하는 경우에 특히 중요합니다.

. CHAP 설정 * 섹션에서 다음을 수행합니다.
+
.. CHAP 노드 세션 인증을 위한 이니시에이터 암호를 입력합니다.
.. CHAP 노드 세션 인증의 대상 암호를 입력합니다.
+

NOTE: 초기자 및 대상 비밀은 달라야 합니다. 이러한 필드를 비워 두면 인증 자격 증명이 생성됩니다.



. 확인 * 을 클릭하여 계정을 만듭니다.




== 계정을 편집합니다

사용자 계정을 편집하여 상태 또는 CHAP 암호를 변경할 수 있습니다. CHAP 설정을 변경하면 호스트와 연결된 볼륨 간의 연결이 끊어질 수 있습니다.

관리 노드에서 영구 볼륨을 사용하는 경우 이러한 볼륨과 연결된 계정의 계정 이름을 수정하지 마십시오.

.단계
. NetApp Element 관리 > 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Accounts * 하위 탭을 선택합니다.
. 편집할 계정의 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 결과 메뉴에서 * Edit * 를 선택합니다.
. 필요에 따라 다음을 변경합니다.
+
.. 계정의 액세스 상태를 편집합니다.
+

IMPORTANT: 액세스 권한을 * Locked * 로 변경하면 계정에 대한 모든 iSCSI 연결이 종료되고 계정에 더 이상 액세스할 수 없습니다. 계정과 연결된 볼륨은 유지되지만 볼륨은 iSCSI를 검색할 수 없습니다.

.. 노드 세션 인증에 사용되는 이니시에이터 암호 또는 타겟 암호 자격 증명을 편집합니다.
+

NOTE: 자격 증명을 변경하지 않으면 자격 증명은 그대로 유지됩니다. 자격 증명 필드를 비워 두면 새 암호가 생성됩니다.



. 확인 * 을 클릭합니다.




== 계정을 삭제합니다

NetApp Element 관리 확장 지점을 사용하여 사용자 계정을 삭제할 수 있습니다.

계정과 연결된 모든 볼륨을 삭제 및 제거하거나 볼륨을 다른 계정에 다시 할당합니다.


IMPORTANT: 관리 노드에서 영구 볼륨을 사용하는 경우 이러한 볼륨과 연결된 계정을 삭제하지 마십시오.

.단계
. NetApp Element 관리 > 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Accounts * 하위 탭을 선택합니다.
. 삭제할 계정의 확인란을 선택합니다.
. 작업 * 을 클릭합니다.
. 결과 메뉴에서 * 삭제 * 를 선택합니다.
. 작업을 확인합니다.




== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 문서"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]

