---
sidebar: sidebar 
permalink: vcp_task_reports_overview.html 
summary: VMware vCenter Server용 NNetApp Element Plug-in의 보고 페이지를 사용하여 클러스터의 구성 요소 및 성능에 대한 정보를 봅니다. 
keywords: netapp, hci, vcp, vcenter, element, monitor, report 
---
= 개요 페이지에서 전체 클러스터 상태를 모니터링합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
전체 용량, 효율성 및 성능을 포함하여 선택한 클러스터에 대한 고급 클러스터 정보를 보려면 VMware vCenter Server용 NetApp Element 플러그인 의 NetApp Element 관리 확장 지점에서 보고 탭의 개요 페이지에서 확인하십시오.

.단계
. vCenter 플러그인에서 * Reporting * 탭을 엽니다.
+
** Element vCenter 플러그인 5.0부터 * NetApp Element 원격 플러그인 > 관리 > 보고 * 를 선택합니다.
** Element vCenter 플러그인 4.10 및 이전 버전의 경우 * NetApp Element 관리 > 보고 * 를 선택합니다.


. 개요 * 페이지의 데이터를 모니터링합니다.




== 보고 개요 페이지 데이터

보고 개요 페이지에 다음 데이터가 나타납니다.

* * 클러스터 용량 *: 블록 스토리지, 메타데이터 및 프로비저닝된 공간에 남아 있는 용량입니다. 임계값 정보를 보려면 진행률 표시줄 위로 포인터를 이동합니다.
* * 클러스터 정보 *: 클러스터 이름, 클러스터에서 실행되는 NetApp Element 소프트웨어 버전, MVIP 및 SVIP 주소, 클러스터의 노드 수, 4K IOPS, 볼륨 및 세션 수와 같은 클러스터 관련 정보입니다.
+
** * 클러스터 이름 *: 클러스터의 이름입니다.
** * 스토리지 IP(SVIP) *: 스토리지 가상 IP 주소(SVIP).
** * 관리 IP(MVIP) *: 관리 가상 IP 주소(MVIP).
** * SVIP VLAN 태그 *: 마스터 SVIP 주소의 VLAN 식별자입니다.
** * MVIP VLAN 태그 *: 마스터 MVIP 주소의 VLAN 식별자입니다.
** * 노드 수 *: 클러스터의 활성 노드 수
** * 클러스터 4K IOPS *: 클러스터에서 초당 읽기/쓸 수 있는 4096(4K) 블록 수입니다.
** * Element OS 버전 *: 클러스터가 실행 중인 NetApp Element 소프트웨어 버전입니다.
** * 볼륨 수 *: 클러스터에서 가상 볼륨을 제외한 총 볼륨 수입니다.
** * 가상 볼륨 수 *: 클러스터의 총 가상 볼륨 수입니다.
** * iSCSI 세션 *: 클러스터에 연결된 iSCSI 세션.
** * Fibre Channel 세션 *: 클러스터에 연결된 Fibre Channel 세션입니다.


* * 클러스터 효율성 *: 씬 프로비저닝, 중복제거, 압축을 고려하면서 활용되는 전체 시스템 용량 기존 스토리지 디바이스에서 씬 프로비저닝, 중복 제거 및 압축 기능을 사용하지 않을 경우의 용량 활용도를 비교하여 클러스터에서 달성된 이점을 계산합니다.
* * 보호 도메인 *: 클러스터에 대한 보호 도메인 모니터링 요약
+

NOTE: 보호 도메인 기능은 2노드 클러스터와 호환되지 않습니다.

+
** * 보호 도메인 모니터링 수준 *: 사용자가 선택한 보호 도메인 복구 수준. 가능한 값은 섀시 또는 노드입니다. 녹색은 클러스터가 선택한 모니터링 수준을 사용할 수 있음을 나타냅니다. 빨간색은 클러스터가 더 이상 선택한 모니터링 수준을 사용할 수 없으며 수정 조치가 필요함을 나타냅니다.
** * 남은 블록 용량 *: 선택한 복구 레벨을 유지하기 위해 남아 있는 블록 용량의 백분율을 나타냅니다.
** * 메타데이터 용량 *: 장애 발생 시 복구할 수 있는 충분한 메타데이터 용량이 있는지 여부와 중단 없는 데이터 가용성을 유지할 수 있는지 여부를 나타냅니다. 정상(녹색)은 선택한 모니터링 레벨을 유지하기에 충분한 메타데이터가 클러스터에 있음을 나타냅니다. 전체(빨간색)는 클러스터가 더 이상 선택한 모니터링 수준을 수행할 수 없고 수정 조치가 필요함을 나타냅니다.


* * 프로비저닝된 IOPS *: 클러스터에서 볼륨 IOPS가 오버 프로비저닝되는 방식 요약 프로비저닝된 IOPS 계산은 클러스터의 모든 볼륨에 대한 총 최소 IOPS, 최대 IOPS 및 버스트 IOPS의 합을 클러스터에 대한 최대 IOPS로 나눈 값으로 결정됩니다.
+

NOTE: 예를 들어, 클러스터에 최소 IOPS가 500이고 최대 IOPS가 15,000이고 버스트 IOPS가 15,000인 볼륨 4개가 있는 경우 총 최소 IOPS 수는 2,000이고, 총 최대 IOPS는 60,000이며, 총 버스트 IOPS는 60,000입니다. 클러스터의 최대 IOPS가 50,000인 경우 다음과 같은 계산이 가능합니다. * 최소 IOPS *:2000/50000 = 0.04x * 최대 IOPS *:60000/50000 = 1.20x * 버스트 IOPS *:60000/50000 = 1.20x 1.00x 1.00x 용량이 클러스터의 IOPS와 동일한 기준입니다.

* * 클러스터 상태 *: 클러스터 상태의 하드웨어, 용량 및 보안 구성 요소입니다. 색상 코드는 다음을 나타냅니다.
+
** * 녹색 *: 정상
** * 노란색 *: 긴급
** * 빨간색 *: 오류


* * 클러스터 입력/출력 *: 클러스터에서 현재 실행 중인 I/O. 이 값은 현재 I/O 측정에 대한 이전 I/O 측정값을 기준으로 계산됩니다. 그래프에 표시된 측정값은 다음과 같습니다.
+
** * 총 *: 시스템에서 발생하는 읽기 및 쓰기 IOPS의 결합.
** * 읽기 *: 발생하는 읽기 IOPS 수입니다.
** * 쓰기 *: 쓰기 IOPS 수입니다.


* * 클러스터 처리량 *: 클러스터의 읽기, 쓰기 및 총 대역폭에 대한 대역폭 작업:
+
** * 총 *: 클러스터에서 읽기 및 쓰기 작업에 모두 사용되는 총 MB/s입니다.
** * 읽기 *: 클러스터의 읽기 작업(MB/s)입니다.
** * 쓰기 *: 클러스터에 대한 쓰기 작업(MB/s)입니다.


* * 성능 활용률 *: 사용 중인 클러스터 IOPS의 비율입니다. 예를 들어, 100K IOPS에서 실행되는 250K IOPS 클러스터는 40%의 소비량으로 표시됩니다.




== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 문서"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]

