---
sidebar: sidebar 
permalink: vcp_task_protect_snapshots_schedules.html 
summary: 플러그인을 사용하여 스냅샷 스케줄을 생성합니다. 
keywords: netapp, hci, vcp, vcenter, element, protect, snapshots, schedule 
---
= 스냅샷 스케줄을 생성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
지정된 날짜 및 시간 간격에 따라 볼륨의 스냅샷이 자동으로 발생하도록 예약할 수 있습니다. 단일 볼륨 스냅샷이나 그룹 스냅샷이 자동으로 실행되도록 예약할 수 있습니다.

스냅샷 스케줄을 생성할 때 볼륨이 복제되는 경우 생성된 스냅샷을 원격 NetApp Element 스토리지 시스템에 저장할 수 있습니다.


NOTE: 일정은 UTC + 0 시간으로 생성됩니다. 표준 시간대를 기준으로 스냅샷이 실행될 실제 시간을 조정해야 할 수 있습니다.

*  a snapshot schedule
*  snapshot schedule details
*  a snapshot schedule
*  a snapshot schedule
*  a snapshot schedule




== 스냅샷 스케줄을 생성합니다

지정된 간격으로 볼륨 또는 볼륨의 스냅샷이 자동으로 발생하도록 예약할 수 있습니다.

스냅샷 스케줄을 구성할 때 해당 월의 일 또는 일을 기준으로 시간 간격 중에서 선택할 수 있습니다. 다음 스냅샷이 발생하기 전 일, 시간 및 분을 지정할 수도 있습니다.

5분 동안 나눌 수 없는 기간에 스냅샷을 실행하도록 예약하는 경우 5분 동안 나눌 수 있는 다음 기간에 스냅샷이 실행됩니다. 예를 들어 스냅샷을 12:42:00 UTC에서 실행하도록 예약하는 경우 12:45:00 UTC에서 실행됩니다. 5분 미만의 간격으로 실행되도록 스냅샷을 예약할 수 없습니다.

.단계
. vCenter 플러그인에서 * NetApp Element 관리 * > * 보호 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 사용할 클러스터가 탐색 모음에서 선택되었는지 확인합니다.

. Schedules * 하위 탭을 선택합니다.
. Create Schedule * 을 선택합니다.
. 볼륨 ID CSV * 필드에 스냅샷 일정 작업에 포함할 단일 볼륨 ID 또는 쉼표로 구분된 볼륨 ID 목록을 입력합니다.
. 일정 이름을 입력합니다.
. 일정 유형을 선택하고 세부 정보를 구성합니다.
. (선택 사항) 일정을 무기한으로 반복하려면 * 반복 일정 * 을 선택합니다.
. (선택 사항) 새 스냅샷 이름 필드에 새 스냅샷의 이름을 입력합니다.
+

NOTE: 이름을 입력하지 않으면 스냅샷이 생성된 날짜와 시간을 사용하여 기본 스냅샷 이름이 생성됩니다.

. (선택 사항) 상위 볼륨이 페어링될 때 스냅샷이 복제되도록 하려면 * 쌍으로 된 경우 복제에 스냅샷 포함 * 을 선택합니다.
. 스냅샷의 보존 기간으로 다음 중 하나를 선택합니다.
+
** * 영구 보관 *: 시스템의 스냅샷을 무기한 유지합니다.
** * 보존 기간 설정 *: 시스템에서 스냅샷을 보존할 시간(일, 시간 또는 분)을 결정합니다.
+

NOTE: 보존 기간을 설정할 때 현재 시간에 시작하는 기간을 선택합니다. (보존은 스냅샷 생성 시간으로부터 계산되지 않습니다.)



. OK * 를 선택합니다.




== 스냅샷 스케줄 세부 정보를 봅니다

스냅샷 스케줄 세부 정보를 확인할 수 있습니다.

.단계
. vCenter 플러그인에서 * NetApp Element 관리 * > * 보호 * 를 선택합니다.
+

NOTE: 둘 이상의 클러스터가 추가된 경우 보려는 클러스터가 탐색 모음에서 선택되었는지 확인합니다.

. Schedules * 페이지를 선택합니다.
. 스케줄 세부 정보를 확인합니다.




== 스냅샷 스케줄을 편집합니다

기존 스냅샷 스케줄을 수정할 수 있습니다. 수정 후 다음 번에 스케줄이 실행될 때 업데이트된 속성이 사용됩니다. 원래 스케줄에 의해 생성된 모든 스냅샷은 스토리지 시스템에 남아 있습니다.

.단계
. NetApp Element 관리 > 보호 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Schedules * 하위 탭을 클릭합니다.
. 편집할 스냅샷 스케줄의 확인란을 선택합니다.
. 작업 * 을 클릭합니다.
. 결과 메뉴에서 * Edit * 를 선택합니다.
. 볼륨 ID CSV * 필드에서 스냅샷 작업에 현재 포함되어 있는 단일 볼륨 ID 또는 쉼표로 구분된 볼륨 ID 목록을 수정합니다.
. (선택 사항) 활성 일정을 일시 중지하거나 일시 중지된 일정을 다시 시작하려면 * 수동 일정 일시 중지 * 확인란을 선택합니다.
. (선택 사항) * New Schedule Name * 필드에 일정에 다른 이름을 입력합니다.
. (선택 사항) 현재 일정 유형을 다음 중 하나로 변경합니다.
+
.. * Days of Week *: 스냅샷을 생성할 요일을 하나 더 선택하고 시간을 선택합니다.
.. * Days of Month * (월 일 수): 스냅샷을 생성할 월 및 일 중 하나 이상을 선택합니다.
.. * 시간 간격 *: 스냅샷 간 일 수, 시간 및 분을 기준으로 스케줄을 실행할 간격을 선택합니다.


. (선택 사항) 스냅샷 스케줄을 무기한 반복하려면 * recurrent Schedule * 을 선택합니다.
. (선택 사항) * New Snapshot Name * 필드에 스케줄에 따라 정의된 스냅샷의 이름을 입력하거나 수정합니다.
+

NOTE: 필드를 비워 두면 스냅샷 생성 날짜와 시간이 이름으로 사용됩니다.

. (선택 사항) 상위 볼륨이 페어링될 때 복제에 스냅샷이 캡처되도록 * Include snapshots in replication when paired * 확인란을 선택합니다.
. (선택 사항) 스냅샷의 보존 기간으로 다음 중 하나를 선택합니다.
+
** * 영구 보관 *: 시스템의 스냅샷을 무기한 유지합니다.
** * 보존 기간 설정 *: 시스템에서 스냅샷을 보존할 시간(일, 시간 또는 분)을 결정합니다.
+

NOTE: 보존 기간을 설정할 때 현재 시간에 시작되는 기간을 선택합니다(스냅샷 생성 시간으로부터 보존이 계산되지 않음).



. 확인 * 을 클릭합니다.




== 스냅샷 스케줄을 복제합니다

스냅샷 스케줄의 복제본을 만들어 새 볼륨에 할당하거나 다른 용도로 사용할 수 있습니다.

.단계
. NetApp Element 관리 > 보호 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Schedules * 하위 탭을 클릭합니다.
. 복제할 스냅샷 스케줄에 대한 확인란을 선택합니다.
. 작업 * 을 클릭합니다.
. 결과 메뉴에서 * 복사 * 를 클릭합니다. 스케줄의 현재 속성이 채워진 스케줄 복사 대화 상자가 나타납니다.
. (선택 사항) 스케줄 복제본에 대한 이름과 업데이트 속성을 입력합니다.
. 확인 * 을 클릭합니다.




== 스냅샷 스케줄을 삭제합니다

스냅샷 스케줄을 삭제할 수 있습니다. 스케줄을 삭제한 후에는 예약된 스냅샷이 실행되지 않습니다. 스케줄에 따라 생성된 모든 스냅샷은 스토리지 시스템에 남아 있습니다.

.단계
. NetApp Element 관리 > 보호 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Schedules * 하위 탭을 클릭합니다.
. 삭제할 스냅샷 스케줄의 확인란을 선택합니다.
. 작업 * 을 클릭합니다.
. 결과 메뉴에서 * 삭제 * 를 클릭합니다.
. 작업을 확인합니다.




== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 문서"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]

