---
sidebar: sidebar 
permalink: vcp_task_qos_policies.html 
summary: 스토리지 클러스터의 볼륨에 적용할 QoS 정책을 설정 및 수정할 수 있습니다. 
keywords: netapp, qos policy, quality of service, qos policies, vcp, vcenter, element 
---
= 볼륨 QoS 정책 생성 및 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
QoS(서비스 품질) 정책을 사용하면 여러 볼륨에 적용할 수 있는 표준화된 서비스 품질 설정을 생성하여 저장할 수 있습니다. QoS 정책을 사용하려면 선택한 클러스터가 Element 10.0 이상이어야 합니다. 그렇지 않으면 QoS 정책 기능을 사용할 수 없습니다.

NetApp Element 관리 확장 지점을 사용하여 다음 작업을 완료하여 QoSSIOC를 구성 및 관리할 수 있습니다.

* <<Create a QoS policy>>
* <<Apply a QoS policy to volumes>>
* <<Change the QoS policy association of a volume>>
* <<Edit a QoS policy>>
* <<Delete a QoS policy>>




== QoS 정책을 생성합니다

QoS 정책을 생성한 후 동일한 성능이 필요한 볼륨에 적용할 수 있습니다.


NOTE: QoSSIOC 자동화 및 QoS 정책을 함께 사용해서는 안 됩니다. QoS 정책을 사용하는 경우 QoSSIOC를 활성화하지 마십시오. QoSSIOC는 볼륨 QoS 설정에 대한 QoS 값을 재정의하고 조정합니다.

.단계
. NetApp Element 관리 > 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. QoS Policies * 하위 탭을 클릭합니다.
. QoS 정책 생성 * 을 클릭합니다.
. 정책 이름 * 을 입력합니다.
+

TIP: 이름 지정 모범 사례를 설명합니다. 이 기능은 사용자 환경에서 여러 클러스터 또는 vCenter Server를 사용하는 경우에 특히 중요합니다.

. 최소 IOPS, 최대 IOPS 및 버스트 IOPS 값을 입력합니다.
. 확인 * 을 클릭합니다.




== 볼륨에 QoS 정책을 적용합니다

기존 QoS 정책을 여러 볼륨에 적용할 수 있습니다. 정책을 하나 이상의 볼륨에 일괄 적용하려는 경우 이 프로세스를 사용합니다.

일괄 적용하려는 QoS 정책은 입니다 <<Create a QoS policy,작성됨>>.

.단계
. NetApp Element 관리 > 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. 볼륨 * 하위 탭을 클릭합니다.
. QoS 정책을 적용할 각 볼륨의 확인란을 선택합니다.
. 작업 * 을 클릭합니다.
. 결과 메뉴에서 * QoS 정책 적용 * 을 선택합니다.
. 대화 상자의 드롭다운 목록에서 QoS 정책을 선택하여 선택한 볼륨에 적용합니다.
. 확인 * 을 클릭합니다.




== 볼륨의 QoS 정책 연결을 변경합니다

볼륨에서 QoS 정책 연결을 제거하거나 다른 QoS 정책 또는 사용자 지정 QoS를 선택할 수 있습니다.

수정하려는 볼륨은 입니다 <<Apply a QoS policy to volumes,연결됨>> QoS 정책을 사용합니다.

.단계
. NetApp Element 관리 > 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. 볼륨 * 하위 탭을 클릭합니다.
. 수정하려는 QoS 정책이 포함된 볼륨의 확인란을 선택합니다.
. 작업 * 을 클릭합니다.
. 결과 메뉴에서 * Edit * 를 선택합니다.
. 대화 상자의 * 서비스 품질 * 아래에서 새 QoS 정책 또는 볼륨에 적용할 사용자 지정 설정을 선택합니다.
. 사용자 지정 설정을 선택한 경우 * 최소 IOPS *, * 최대 IOPS * 및 * 버스트 IOPS * 값을 수정합니다.
+

NOTE: 기본 IOPS 값을 복원하려면 * 기본 QoS 재설정 * 을 클릭할 수도 있습니다.

. 확인 * 을 클릭합니다.




== QoS 정책을 편집합니다

기존 QoS 정책의 이름을 변경하거나 정책과 연결된 값을 편집할 수 있습니다. QoS 정책 성능 값을 변경하면 정책에 연결된 모든 볼륨의 QoS에 영향을 줍니다.

.단계
. NetApp Element 관리 > 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. QoS Policies * 하위 탭을 클릭합니다.
. 편집할 QoS 정책의 확인란을 선택합니다.
. 작업 * 을 클릭합니다.
. 결과 메뉴에서 * Edit * 를 선택합니다.
. QoS 정책 편집 * 대화 상자에서 필요에 따라 다음 속성을 수정합니다.
+
** * 정책 이름 *: QoS 정책에 대한 사용자 정의 이름입니다.
** * 최소 IOPS *: 볼륨에 대해 보장된 최소 IOPS 수입니다.
** * 최대 IOPS *: 볼륨에 허용되는 최대 IOPS 수입니다.
** * 버스트 IOPS *: 짧은 기간 동안 볼륨에 허용되는 최대 IOPS 수입니다. 기본값 = 15,000.
+

NOTE: 기본 QoS 재설정 을 클릭하여 기본 IOPS 값을 복원할 수도 있습니다.



. 확인 * 을 클릭합니다.




== QoS 정책을 삭제합니다

QoS 정책이 더 이상 필요하지 않은 경우 삭제할 수 있습니다. QoS 정책을 삭제할 경우 정책에 연결된 모든 볼륨은 정책에 의해 이전에 정의된 QoS 값을 개별 볼륨 QoS로 유지합니다. 삭제된 QoS 정책과의 연결이 제거됩니다.

.단계
. NetApp Element 관리 > 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. QoS Policies * 하위 탭을 클릭합니다.
. 삭제할 QoS 정책의 확인란을 선택합니다.
. 작업 * 을 클릭합니다.
. 결과 메뉴에서 * 삭제 * 를 선택합니다.
. 작업을 확인합니다.


[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 문서"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]

