---
sidebar: sidebar 
permalink: vcp_task_add_manage_drive.html 
summary: 플러그인을 사용하여 클러스터에 드라이브를 추가하고 관리할 수 있습니다. 
keywords: netapp, drives, add, manage, remove, view vcp, vcenter, element 
---
= 드라이브 추가 및 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Element 관리 확장 지점을 사용하여 클러스터에 드라이브를 추가하고, 기존 드라이브를 보고, 드라이브를 제거할 수 있습니다.

*  available drives to a cluster
*  drive details
*  a drive




== 사용 가능한 드라이브를 클러스터에 추가합니다

NetApp Element 관리 확장 지점을 사용하여 클러스터에 드라이브를 추가할 수 있습니다. 클러스터에 노드를 추가하거나 기존 노드에 새 드라이브를 설치하면 드라이브가 자동으로 "사용 가능"으로 등록됩니다. 각 드라이브가 클러스터에 참여하려면 먼저 클러스터에 드라이브를 추가해야 합니다.

다음 조건이 충족되면 사용 가능 목록에 드라이브가 표시되지 않습니다.

* 드라이브는 활성, 제거, 삭제 또는 실패 상태입니다.
* 드라이브가 속한 노드가 'Pending' 상태입니다.


.단계
. NetApp Element 관리 > 클러스터 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Drives * 하위 탭의 드롭다운 목록에서 * Available * 을 선택하여 사용 가능한 드라이브 목록을 표시합니다.
. 다음과 같이 드라이브를 추가합니다.
+
.. 추가할 각 드라이브에 대한 확인란을 선택합니다.
.. 드라이브 추가 * 를 클릭합니다.


. 추가하려는 드라이브의 세부 정보를 검토하고 작업을 확인합니다.




== 드라이브 세부 정보를 봅니다

NetApp Element 관리 확장 지점에서 클러스터 탭의 드라이브 페이지에 있는 활성 보기를 사용하여 클러스터의 활성 드라이브 목록을 볼 수 있습니다. 드롭다운 필터를 사용하여 사용 가능한 옵션을 선택하여 보기를 변경할 수 있습니다.

클러스터를 처음 초기화하면 활성 드라이브 목록이 비어 있습니다. 새 클러스터를 생성한 후 클러스터에 할당되지 않고 Available 탭에 나열된 드라이브를 추가할 수 있습니다.

.단계
. NetApp Element 관리 > 클러스터 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Drives * 하위 탭을 선택합니다.
. 활성 * 보기를 선택합니다.
. 시스템에서 현재 활성 상태인 드라이브의 세부 정보를 봅니다.
+
드라이브 ID, 각 드라이브의 용량 및 상태, 드라이브가 상주하는 노드에 대한 정보 등의 정보를 볼 수 있습니다.





== 드라이브를 분리합니다

NetApp Element 관리 확장 지점을 사용하여 클러스터에서 드라이브를 제거할 수 있습니다. 클러스터 용량을 줄이거나 서비스 수명이 거의 다 된 드라이브를 교체할 준비를 할 때 이 작업을 수행할 수 있습니다. 드라이브를 제거하면 드라이브가 오프라인 상태가 됩니다. 드라이브에서 데이터가 제거되기 전에 클러스터의 다른 드라이브로 마이그레이션됩니다. 시스템의 다른 활성 드라이브로 데이터를 마이그레이션하는 데는 용량 활용률과 클러스터의 활성 I/O에 따라 몇 분에서 한 시간까지 걸릴 수 있습니다.

Failed(실패) 상태의 드라이브를 제거하면 드라이브가 Available(사용 가능) 또는 Active(활성) 상태로 복귀되지 않습니다. 대신 클러스터에서 드라이브를 사용할 수 없습니다.

.단계
. NetApp Element 관리 > 클러스터 * 를 선택합니다.
. 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.
. 드롭다운 목록에서 * All * 을 선택하여 전체 드라이브 목록을 봅니다.
. 다음과 같이 드라이브를 제거합니다.
+
.. 제거할 각 드라이브의 확인란을 선택합니다.
.. 드라이브 제거 * 를 클릭합니다.


. 작업을 확인합니다.
+

NOTE: 노드를 제거하기 전에 활성 드라이브를 제거할 용량이 충분하지 않으면 드라이브 제거를 확인할 때 오류 메시지가 나타납니다.


