---
sidebar: sidebar 
permalink: vcp_task_protect_remote_replication.html 
summary: 실시간 복제를 통해 볼륨 데이터의 원격 복사본을 신속하게 생성할 수 있습니다. 
keywords: netapp, hci, vcp, vcenter, element, protect, replication, remote, cluster 
---
= 클러스터 간에 원격 복제를 수행합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Element 소프트웨어를 실행하는 클러스터의 경우 실시간 복제를 통해 볼륨 데이터의 원격 복사본을 신속하게 생성할 수 있습니다. 스토리지 클러스터를 최대 4개의 다른 스토리지 클러스터와 페어링할 수 있습니다.

장애 조치 및 장애 복구 시나리오를 위해 클러스터 쌍의 클러스터 중 하나에서 볼륨 데이터를 동기 또는 비동기식으로 복제할 수 있습니다. 실시간 원격 복제를 활용하려면 먼저 2개의 NetApp Element 클러스터를 페어링한 다음 각 클러스터에서 볼륨을 페어링해야 합니다.

.무엇을 &#8217;필요로 할거야
* 플러그인에 클러스터를 하나 이상 추가했는지 확인합니다.
* 페어링된 클러스터의 관리 및 스토리지 네트워크 모두에 있는 모든 노드 IP 주소가 서로 라우팅되는지 확인합니다.
* 페어링된 모든 노드의 MTU가 동일하고 클러스터 간 종단 간 지원이 지원되는지 확인합니다.
* 클러스터의 NetApp Element 소프트웨어 버전 간 차이가 주요 버전 1개를 넘지 않도록 하십시오. 차이가 크면 클러스터 중 하나를 업그레이드하여 데이터 복제를 수행해야 합니다.



NOTE: NetApp은 데이터 복제 시 WAN 가속기 어플라이언스를 사용하지 않았습니다. 이러한 어플라이언스는 데이터를 복제하는 두 클러스터 간에 구축될 경우 압축 및 중복 제거를 방해할 수 있습니다. 프로덕션 환경에 배포하기 전에 WAN 가속기 어플라이언스의 효과를 완벽하게 검증해야 합니다.

.단계
.  clusters
.  volumes
.  volume replication
.  a volume relationship after replication
.  volume relationships




== 클러스터 쌍

실시간 복제 기능을 사용하려면 먼저 두 클러스터를 페어링해야 합니다. 두 클러스터를 페어링하고 연결한 후, 한 클러스터의 활성 볼륨을 구성하여 두 번째 클러스터에 지속적으로 복제함으로써 CDP(무중단 데이터 보호)를 제공할 수 있습니다.

두 클러스터에 대한 클러스터 관리자 액세스 권한이 있는 경우 대상 클러스터의 MVIP를 사용하여 소스 클러스터와 타겟 클러스터를 페어링할 수 있습니다. 클러스터 관리자 액세스 권한이 클러스터 쌍의 한 클러스터에서만 사용 가능한 경우 타겟 클러스터에서 페어링 키를 사용하여 클러스터 페어링을 완료할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 페어링되는 하나 또는 두 클러스터에 대해 클러스터 관리자 권한이 필요합니다.
* 클러스터 간 왕복 지연 시간이 2000ms 미만인지 확인합니다.
* 클러스터의 NetApp Element 소프트웨어 버전 간 차이가 주요 버전 1개를 넘지 않도록 하십시오.
* 페어링된 클러스터의 모든 노드 IP가 서로 라우팅되는지 확인합니다.



NOTE: 클러스터 페어링은 관리 네트워크의 노드 간에 완벽하게 연결되어 있어야 합니다. 복제를 수행하려면 스토리지 클러스터 네트워크의 개별 노드 간에 접속해야 합니다.

볼륨 복제를 위해 하나의 NetApp Element 클러스터를 최대 4개의 다른 클러스터와 페어링할 수 있습니다. 클러스터 그룹 내의 클러스터를 서로 페어링할 수도 있습니다.

다음 방법 중 하나를 선택합니다.

*  clusters using known credentials
*  clusters with a pairing key




=== 알려진 자격 증명을 사용하여 클러스터를 페어링합니다

한 클러스터의 MVIP를 사용하여 다른 클러스터와의 연결을 설정하여 실시간 복제를 위해 두 클러스터를 페어링할 수 있습니다. 이 방법을 사용하려면 두 클러스터 모두에서 클러스터 관리자 액세스 권한이 필요합니다.

클러스터를 페어링하기 전에 클러스터 관리자 사용자 이름 및 암호를 사용하여 클러스터 액세스를 인증합니다.

MVIP를 알 수 없거나 클러스터에 액세스할 수 없는 경우 페어링 키를 생성하여 클러스터를 페어링하고 키를 사용하여 두 클러스터를 페어링할 수 있습니다. 자세한 내용은 을 참조하십시오  clusters with a pairing key.

.단계
. 로컬 클러스터가 포함된 vCenter에서 * NetApp Element 관리 * > * 보호 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Cluster Pairs * 하위 탭을 선택합니다.
. Create Cluster Pairing * 을 선택합니다.
. 다음 중 하나를 선택합니다.
+
** * Registered Cluster *: 페어링의 원격 클러스터가 Element vCenter 플러그인의 동일한 인스턴스에 의해 제어되는 경우 이 옵션을 선택합니다.
** * 자격 증명 클러스터 *: 원격 클러스터에 Element vCenter 플러그인 구성 이외의 자격 증명이 있는 경우 이 옵션을 선택합니다.


. Registered Cluster * 를 선택한 경우 사용 가능한 클러스터 목록에서 클러스터를 선택하고 * Pair * 를 클릭합니다.
. 자격 있는 클러스터 * 를 선택한 경우 다음을 수행합니다.
+
.. 원격 클러스터 MVIP 주소를 입력합니다.
.. 클러스터 관리자 사용자 이름을 입력합니다.
.. 클러스터 관리자 암호를 입력합니다.
.. 페어링 시작 * 을 선택합니다.


. 작업이 완료되고 클러스터 쌍 페이지가 표시되면 클러스터 쌍이 연결되어 있는지 확인합니다.
. (선택 사항) 원격 클러스터에서 * NetApp Element 관리 * > * 보호 * > * 클러스터 쌍 * 을 선택하거나 Element 웹 UI를 사용하여 클러스터 쌍이 연결되었는지 확인합니다.




=== 클러스터를 페어링 키와 페어링합니다

원격 클러스터가 아닌 로컬 클러스터에 대한 Cluster Admin 액세스 권한이 있는 경우 페어링 키를 사용하여 클러스터를 페어링할 수 있습니다. 로컬 클러스터에서 페어링 키가 생성된 후 원격 사이트의 클러스터 관리자에게 안전하게 전송되어 연결을 설정하고 실시간 복제를 위해 클러스터 페어링을 완료합니다.

이 절차에서는 로컬 사이트와 원격 사이트에서 vCenter를 사용하여 두 클러스터 간에 클러스터를 페어링하는 방법에 대해 설명합니다. vCenter 플러그인으로 제어되지 않는 클러스터의 경우 또는 를 사용할 수 있습니다 https://docs.netapp.com/us-en/element-software/storage/task_replication_pair_cluster_using_pairing_key.html["클러스터 페어링을 시작하거나 완료합니다"] Element 웹 UI 사용

.단계
. 로컬 클러스터가 포함된 vCenter에서 * NetApp Element 관리 * > * 보호 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Cluster Pairs * 하위 탭을 선택합니다.
. Create Cluster Pairing * 을 선택합니다.
. 액세스할 수 없는 클러스터 * 를 선택합니다.
. 키 생성 * 을 선택합니다.
+

NOTE: 이렇게 하면 페어링을 위한 텍스트 키가 생성되고 로컬 클러스터에 구성되지 않은 클러스터 쌍이 생성됩니다. 이 절차를 완료하지 않으면 클러스터 쌍을 수동으로 삭제해야 합니다.

. 클러스터 페어링 키를 클립보드에 복사합니다.
. 닫기 * 를 선택합니다.
. 원격 클러스터 사이트에서 클러스터 관리자가 페어링 키를 액세스할 수 있도록 합니다.
+

NOTE: 클러스터 페어링 키에는 원격 복제를 위한 볼륨 연결을 허용하는 MVIP 버전, 사용자 이름, 암호 및 데이터베이스 정보가 포함되어 있습니다. 이 키는 안전한 방식으로 취급해야 하며 사용자 이름 또는 암호에 우발적이거나 안전하지 않은 액세스를 허용하는 방식으로 저장되지 않아야 합니다.

+

IMPORTANT: 페어링 키의 문자를 수정하지 마십시오. 키를 수정하면 키가 무효화됩니다.

. 원격 클러스터가 포함된 vCenter에서 * NetApp Element 관리 * > * 보호 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

+

NOTE: Element UI를 사용하여 페어링을 완료할 수도 있습니다.

. Cluster Pairs * 하위 탭을 선택합니다.
. 클러스터 페어링 완료 * 를 선택합니다.
+

NOTE: 다음 단계로 진행하기 전에 로딩 스피너가 사라질 때까지 기다리십시오. 페어링 프로세스 중에 예기치 않은 오류가 발생하면 로컬 및 원격 클러스터에서 구성되지 않은 클러스터 쌍을 확인하고 수동으로 삭제한 다음 다시 페어링을 수행합니다.

. 로컬 클러스터의 페어링 키를 * 클러스터 페어링 키 * 필드에 붙여 넣습니다.
. 클러스터 페어링 * 을 선택합니다.
. 작업이 완료되고 * 클러스터 쌍 * 페이지가 표시되면 클러스터 쌍이 연결되어 있는지 확인합니다.
. 클러스터 쌍이 연결되었는지 확인하려면 원격 클러스터에서 * NetApp Element 관리 * > * 보호 * 를 선택하거나 Element UI를 사용하십시오.




=== 클러스터 쌍 연결을 확인합니다

클러스터 페어링이 완료된 후 클러스터 쌍 연결을 확인하여 복제가 성공했는지 확인할 수 있습니다.

.단계
. 로컬 클러스터에서 * 데이터 보호 * > * 클러스터 쌍 * 을 선택합니다.
. 클러스터 쌍이 연결되어 있는지 확인합니다.
. 로컬 클러스터와 * Cluster Pairs * 창으로 다시 이동하여 클러스터 쌍이 연결되었는지 확인합니다.




== 볼륨을 페어링합니다

클러스터 쌍의 클러스터 간에 연결을 설정한 후에는 한 클러스터의 볼륨을 해당 쌍의 다른 클러스터의 볼륨과 페어링할 수 있습니다.

다음 방법 중 하나를 사용하여 볼륨을 페어링할 수 있습니다.

*  volumes using known credentials: 두 클러스터에 대해 알려진 자격 증명을 사용합니다
*  volumes using a pairing key: 소스 클러스터에서만 클러스터 자격 증명을 사용할 수 있는 경우 페어링 키를 사용합니다.
*  target volumes and pair them with local volumes: 두 클러스터에 대한 자격 증명을 알고 있는 경우 원격 클러스터에서 복제 타겟 볼륨을 생성하여 소스 클러스터와 페어링합니다.


볼륨 페어링 관계가 설정되면 복제 대상이 되는 볼륨을 확인해야 합니다.

*  a replication source and target to paired volumes


.무엇을 &#8217;필요로 할거야
* 클러스터 쌍의 클러스터 간에 연결을 설정해야 합니다.
* 페어링되는 하나 또는 두 클러스터에 대한 클러스터 관리자 권한이 있어야 합니다.




=== 알려진 자격 증명을 사용하여 볼륨을 페어링합니다

로컬 볼륨을 원격 클러스터의 다른 볼륨과 페어링할 수 있습니다. 볼륨을 페어링할 두 클러스터에 클러스터 관리자 액세스 권한이 있는 경우 이 방법을 사용합니다. 이 방법은 원격 클러스터에 있는 볼륨의 볼륨 ID를 사용하여 연결을 시작합니다.

.시작하기 전에
* 원격 클러스터에 대한 클러스터 관리자 자격 증명이 있습니다.
* 볼륨이 포함된 클러스터가 페어링되었는지 확인합니다.
* 이 프로세스 중에 새 볼륨을 생성하려는 경우가 아니면 원격 볼륨 ID를 알고 있습니다.
* 로컬 볼륨을 소스로 설정하려면 볼륨의 액세스 모드가 읽기/쓰기로 설정되어 있는지 확인합니다.


.단계
. 로컬 클러스터가 포함된 vCenter에서 * NetApp Element 관리 * > * 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. 볼륨 * 하위 탭을 선택합니다.
. Active * 뷰에서 페어링할 볼륨의 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 볼륨 페어링 * 을 선택합니다.
. 다음 중 하나를 선택합니다.
+
** * 볼륨 생성 *: 원격 클러스터에서 복제 타겟 볼륨을 생성하려면 이 옵션을 선택합니다. 이 방법은 Element vCenter 플러그인으로 제어되는 원격 클러스터에서만 사용할 수 있습니다.
** * 볼륨 선택 *: 대상 볼륨에 대한 원격 클러스터가 Element vCenter 플러그인으로 제어되는 경우 이 옵션을 선택합니다.
** * 볼륨 ID *: 타겟 볼륨의 원격 클러스터에 Element vCenter 플러그인 구성 이외의 알려진 자격 증명이 있는 경우 이 옵션을 선택합니다.


. 복제 모드 선택:
+
** * 실시간(동기식) *: 쓰기가 소스 클러스터와 타겟 클러스터 모두에서 커밋된 후 클라이언트에 인식됩니다.
** * 실시간(비동기식) *: 소스 클러스터에서 커밋된 쓰기가 클라이언트에 확인됩니다.
** * 스냅샷만 *: 소스 클러스터에서 생성된 스냅샷만 복제됩니다. 소스 볼륨의 활성 쓰기는 복제되지 않습니다.


. 페어링 모드 옵션으로 * 볼륨 생성 * 을 선택한 경우 다음을 수행합니다.
+
.. 드롭다운 목록에서 페어링된 클러스터를 선택합니다.
+

NOTE: 이 작업은 다음 단계에서 선택할 클러스터에서 사용 가능한 계정을 채웁니다.

.. 타겟 클러스터에서 복제 타겟 볼륨의 계정을 선택합니다.
.. 복제 타겟 볼륨 이름을 입력합니다.
+

NOTE: 이 프로세스 중에는 볼륨 크기를 조정할 수 없습니다.



. 페어링 모드 옵션으로 * 볼륨 선택 * 을 선택한 경우 다음을 수행합니다.
+
.. 페어링된 클러스터를 선택하십시오.
+

NOTE: 그러면 다음 단계에서 선택할 클러스터의 사용 가능한 볼륨이 채워집니다.

.. (선택 사항) 볼륨 페어링에서 원격 볼륨을 대상으로 설정하려면 * 원격 볼륨을 복제 타겟으로 설정 * 옵션을 선택합니다. 읽기/쓰기로 설정된 경우 로컬 볼륨은 쌍의 소스가 됩니다.
+

IMPORTANT: 기존 볼륨을 복제 타겟으로 할당할 경우 해당 볼륨의 데이터를 덮어씁니다. 모범 사례로 새 볼륨을 복제 타겟으로 사용해야 합니다.

+

NOTE: 나중에 페어링 프로세스 중에 * 볼륨 * > * 작업 * > * 편집 * 에서 복제 소스 및 대상을 할당할 수도 있습니다. 페어링을 완료하려면 소스와 대상을 할당해야 합니다.

.. 사용 가능한 볼륨 목록에서 볼륨을 선택합니다.


. 페어링 모드 옵션으로 * 볼륨 ID * 를 선택한 경우 다음을 수행합니다.
+
.. 드롭다운 목록에서 페어링된 클러스터를 선택합니다.
.. 클러스터에 플러그인이 등록되어 있지 않은 경우 클러스터 관리자 사용자 ID와 클러스터 관리자 암호를 입력합니다.
.. 볼륨 ID를 입력합니다.
.. 원격 볼륨을 볼륨 페어링의 대상으로 설정하려면 * 원격 볼륨을 복제 대상으로 설정 * 옵션을 선택합니다. 읽기/쓰기로 설정된 경우 로컬 볼륨은 쌍의 소스가 됩니다.
+

IMPORTANT: 기존 볼륨을 복제 타겟으로 할당할 경우 해당 볼륨의 데이터를 덮어씁니다. 모범 사례로 새 볼륨을 복제 타겟으로 사용해야 합니다.

+

NOTE: 나중에 페어링 프로세스 중에 * 볼륨 * > * 작업 * > * 편집 * 에서 복제 소스 및 대상을 할당할 수도 있습니다. 페어링을 완료하려면 소스와 대상을 할당해야 합니다.



. 페어링 * 을 선택합니다.
+

NOTE: 페어링을 확인한 후 두 클러스터가 볼륨 연결 프로세스를 시작합니다. 페어링 프로세스 중에 볼륨 쌍 페이지의 볼륨 상태 열에서 진행 메시지를 볼 수 있습니다.

+

NOTE: 복제 대상으로 볼륨을 아직 할당하지 않은 경우 페어링 구성이 완료되지 않습니다. 볼륨 페어 소스와 타겟이 할당될 때까지 볼륨 페어에 PausedMisconfigured가 표시됩니다. 볼륨 페어링을 완료하려면 소스와 대상을 할당해야 합니다.

. 양쪽 클러스터에서 * 보호 * > * 볼륨 쌍 * 을 선택합니다.
. 볼륨 페어링의 상태를 확인합니다.




=== 페어링 키를 사용하여 볼륨을 페어링합니다

페어링 키를 사용하여 원격 클러스터의 다른 볼륨과 로컬 볼륨을 페어링할 수 있습니다. 소스 클러스터에만 Cluster Admin 액세스 권한이 있는 경우 이 방법을 사용합니다. 이 방법을 사용하면 원격 클러스터에서 볼륨 쌍을 완료하는 데 사용할 수 있는 페어링 키가 생성됩니다.

.시작하기 전에
* 볼륨이 포함된 클러스터가 페어링되었는지 확인합니다.
* * 모범 사례 *: 소스 볼륨을 읽기/쓰기로 설정하고 타겟 볼륨을 복제 타겟으로 설정합니다. 타겟 볼륨에는 데이터가 없어야 하며 크기, 512e 설정 및 QoS 구성과 같은 소스 볼륨의 정확한 특성이 있어야 합니다. 기존 볼륨을 복제 타겟으로 할당할 경우 해당 볼륨의 데이터를 덮어씁니다. 타겟 볼륨의 크기는 소스 볼륨과 같거나 더 클 수 있지만 크기는 작을 수 없습니다.


이 절차에서는 로컬 및 원격 사이트에서 vCenter를 사용하여 두 볼륨 간의 볼륨 페어링에 대해 설명합니다. vCenter 플러그인으로 제어되지 않는 볼륨의 경우 Element 웹 UI를 사용하여 볼륨 페어링을 시작 또는 완료할 수 있습니다.

Element 웹 UI에서 볼륨 페어링을 시작 또는 완료하는 방법에 대한 지침은 을(를) 참조하십시오 https://docs.netapp.com/us-en/element-software/storage/task_replication_pair_volumes_using_a_pairing_key.html["NetApp Element 소프트웨어 설명서"^].


NOTE: 볼륨 페어링 키는 볼륨 정보의 암호화된 버전을 포함하며 중요한 정보를 포함할 수 있습니다. 이 키는 안전한 방법으로만 공유합니다.

.단계
. 로컬 클러스터가 포함된 vCenter에서 * NetApp Element 관리 * > * 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. 볼륨 * 하위 탭을 선택합니다.
. Active * 뷰에서 페어링할 볼륨의 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 볼륨 페어링 * 을 선택합니다.
. 액세스할 수 없는 클러스터 * 를 선택합니다.
. 복제 모드 선택:
+
** * 실시간(동기식) *: 쓰기가 소스 클러스터와 타겟 클러스터 모두에서 커밋된 후 클라이언트에 인식됩니다.
** * 실시간(비동기식) *: 소스 클러스터에서 커밋된 쓰기가 클라이언트에 확인됩니다.
** * 스냅샷만 *: 소스 클러스터에서 생성된 스냅샷만 복제됩니다. 소스 볼륨의 활성 쓰기는 복제되지 않습니다.


. 키 생성 * 을 선택합니다.
+

NOTE: 이렇게 하면 페어링을 위한 텍스트 키가 생성되고 로컬 클러스터에 구성되지 않은 볼륨 쌍이 생성됩니다. 이렇게 하지 않으면 볼륨 쌍을 수동으로 삭제해야 합니다.

. 페어링 키를 클립보드에 복사합니다.
. 닫기 * 를 선택합니다.
. 원격 클러스터 사이트에서 클러스터 관리자가 페어링 키를 액세스할 수 있도록 합니다.
+

NOTE: 볼륨 페어링 키는 안전한 방식으로 취급해야 하며 실수로 또는 비보안 액세스를 허용하는 방식으로 보관해서는 안 됩니다.

+

IMPORTANT: 페어링 키의 문자를 수정하지 마십시오. 키를 수정하면 키가 무효화됩니다.

. 원격 클러스터가 포함된 vCenter에서 * NetApp Element 관리 * > * 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. 볼륨 * 하위 탭을 선택합니다.
. Active * (활성 *) 보기에서 페어링할 볼륨의 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 볼륨 페어링 * 을 선택합니다.
. 클러스터 페어링 완료 * 를 선택합니다.
. 다른 클러스터의 페어링 키를 * 페어링 키 * 상자에 붙여 넣습니다.
. 페어링 완료 * 를 선택합니다.
+

NOTE: 페어링을 확인한 후 두 클러스터가 볼륨 연결 프로세스를 시작합니다. 페어링 프로세스 중에 볼륨 쌍 페이지의 볼륨 상태 열에서 진행 메시지를 볼 수 있습니다. 페어링 프로세스 중에 예기치 않은 오류가 발생하면 로컬 및 원격 클러스터에서 구성되지 않은 클러스터 쌍을 확인하고 수동으로 삭제한 다음 다시 페어링을 수행합니다.

+

IMPORTANT: 복제 대상으로 볼륨을 아직 할당하지 않은 경우 페어링 구성이 완료되지 않습니다. 볼륨 페어 소스와 타겟이 할당될 때까지 볼륨 페어에 "PausedMisconfigured"가 표시됩니다. 볼륨 페어링을 완료하려면 소스와 대상을 할당해야 합니다.

. 양쪽 클러스터에서 * 보호 * > * 볼륨 쌍 * 을 선택합니다.
. 볼륨 페어링의 상태를 확인합니다.
+

NOTE: 페어링 키를 사용하여 페어링된 볼륨은 원격 위치에서 페어링 프로세스가 완료된 후에 나타납니다.





=== 타겟 볼륨을 생성하여 로컬 볼륨과 페어링합니다

원격 클러스터에서 둘 이상의 로컬 볼륨을 연결된 타겟 볼륨과 페어링할 수 있습니다. 이 프로세스는 선택한 각 로컬 소스 볼륨에 대해 원격 클러스터에 복제 타겟 볼륨을 생성합니다. 볼륨이 페어링될 두 클러스터에 대한 Cluster Admin 액세스 권한이 있고 원격 클러스터가 플러그인으로 제어되는 경우 이 방법을 사용합니다.

이 방법은 원격 클러스터에 있는 각 볼륨의 볼륨 ID를 사용하여 하나 이상의 연결을 시작합니다.

.시작하기 전에
* 원격 클러스터에 대한 클러스터 관리자 자격 증명이 있는지 확인합니다.
* 볼륨이 포함된 클러스터가 플러그인을 사용하여 페어링되었는지 확인합니다.
* 원격 클러스터가 플러그인으로 제어되는지 확인합니다.
* 각 로컬 볼륨의 액세스 모드가 읽기/쓰기로 설정되어 있는지 확인합니다.


.단계
. 로컬 클러스터가 포함된 vCenter에서 * NetApp Element 관리 * > * 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. 볼륨 * 하위 탭을 선택합니다.
. Active * 보기에서 페어링할 볼륨을 두 개 이상 선택합니다.
. 작업 * 을 선택합니다.
. 볼륨 페어링 * 을 선택합니다.
. 복제 모드 * 선택:
+
** * 실시간(동기식) *: 쓰기가 소스 클러스터와 타겟 클러스터 모두에서 커밋된 후 클라이언트에 인식됩니다.
** * 실시간(비동기식) *: 소스 클러스터에서 커밋된 쓰기가 클라이언트에 확인됩니다.
** * 스냅샷만 *: 소스 클러스터에서 생성된 스냅샷만 복제됩니다. 소스 볼륨의 활성 쓰기는 복제되지 않습니다.


. 드롭다운 목록에서 페어링된 클러스터를 선택합니다.
. 타겟 클러스터에서 복제 타겟 볼륨의 계정을 선택합니다.
. (선택 사항) 타겟 클러스터의 새 볼륨 이름에 대한 접두사 또는 접미사를 입력합니다.
+

NOTE: 수정된 이름의 샘플 볼륨 이름이 나타납니다.

. Create Pairs * 를 선택합니다.
+

NOTE: 페어링을 확인한 후 두 클러스터가 볼륨 연결 프로세스를 시작합니다. 페어링 프로세스 중에 볼륨 쌍 페이지의 볼륨 상태 열에서 진행 메시지를 볼 수 있습니다. 프로세스가 완료되면 새 타겟 볼륨이 생성되어 원격 클러스터에 연결됩니다.

. 양쪽 클러스터에서 * 보호 * > * 볼륨 쌍 * 을 선택합니다.
. 볼륨 페어링의 상태를 확인합니다.




=== 복제 소스와 타겟을 페어링된 볼륨에 할당합니다

볼륨 페어링 중에 볼륨을 복제 대상으로 할당하지 않은 경우 구성이 완료되지 않습니다. 이 절차를 사용하여 소스 볼륨과 해당 복제 타겟 볼륨을 할당할 수 있습니다. 복제 소스 또는 타겟은 볼륨 쌍의 볼륨일 수 있습니다.

소스 볼륨을 사용할 수 없는 경우 이 절차를 사용하여 소스 볼륨에서 원격 타겟 볼륨으로 데이터를 리디렉션할 수도 있습니다.

소스 볼륨과 타겟 볼륨이 포함된 클러스터에 액세스할 수 있습니다.

이 절차에서는 로컬 및 원격 사이트에서 vCenter를 사용하여 두 클러스터 간에 소스 및 복제 볼륨을 할당하는 방법에 대해 설명합니다. vCenter 플러그인에서 제어하지 않는 볼륨의 경우 또는 를 사용할 수 있습니다 https://docs.netapp.com/us-en/element-software/storage/task_replication_assign_replication_source_and_target_to_paired_volumes.html["소스 또는 복제 볼륨을 할당합니다"] Element 웹 UI 사용

복제 소스 볼륨에 읽기/쓰기 계정 액세스 권한이 있습니다. 복제 타겟 볼륨은 복제 소스에서 읽기/쓰기로 액세스할 수만 있습니다.

* 모범 사례 *: 타겟 볼륨에는 데이터가 없어야 하며 크기, 512e 설정 및 QoS 구성과 같은 소스 볼륨의 정확한 특성이 있어야 합니다. 타겟 볼륨의 크기는 소스 볼륨과 같거나 더 클 수 있지만 크기는 작을 수 없습니다.

.단계
. vCenter Server의 * NetApp Element Management * 확장 지점에서 복제 소스로 사용할 페어링된 볼륨이 포함된 클러스터를 선택합니다.
. NetApp Element 관리 * > * 관리 * 를 선택합니다.
. 볼륨 * 하위 탭을 선택합니다.
. Active * (활성 *) 보기에서 편집할 볼륨의 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 편집 * 을 선택합니다.
. 액세스 드롭다운 목록에서 * 읽기/쓰기 * 를 선택합니다.
+

IMPORTANT: 소스 및 타겟 할당을 반대로 전환하는 경우 이 작업을 수행하면 새 복제 타겟이 할당될 때까지 볼륨 페어가 PausedMisConfigured를 표시합니다. 액세스를 변경하면 볼륨 복제가 일시 중지되고 데이터 전송이 중지됩니다. 두 사이트에서 이러한 변경 내용을 조정했는지 확인합니다.

. OK * 를 선택합니다.
. NetApp Element 관리 * 확장 지점에서 복제 대상으로 사용할 페어링된 볼륨이 포함된 클러스터를 선택합니다.
. NetApp Element 관리 * > * 관리 * 를 선택합니다.
. 볼륨 * 하위 탭을 선택합니다.
. Active * (활성 *) 보기에서 편집할 볼륨의 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 편집 * 을 선택합니다.
. Access * 드롭다운 목록에서 * Replication Target * 을 선택합니다.
+

IMPORTANT: 기존 볼륨을 복제 타겟으로 할당할 경우 해당 볼륨의 데이터를 덮어씁니다. 모범 사례로 새 볼륨을 복제 타겟으로 사용해야 합니다.

. OK * 를 선택합니다.




== 볼륨 복제를 확인합니다

볼륨이 복제된 후에는 소스 볼륨과 타겟 볼륨이 활성 상태인지 확인해야 합니다. 활성 상태인 경우 볼륨이 페어링되고 데이터가 소스에서 타겟 볼륨으로 전송되고 데이터가 동기화됩니다.

.단계
. 페어링의 클러스터 중 하나에서 * NetApp Element 관리 * > * 보호 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Volume Pairs * 하위 탭을 선택합니다.
. 볼륨 상태가 활성인지 확인합니다.




== 복제 후 볼륨 관계를 삭제합니다

복제가 완료되고 볼륨 페어링 관계가 더 이상 필요하지 않으면 볼륨 관계를 삭제할 수 있습니다.

을 참조하십시오  a volume pair.



== 볼륨 관계 관리

복제 일시 중지, 볼륨 페어링 되돌리기, 복제 모드 변경, 볼륨 쌍 삭제, 클러스터 쌍 삭제 등 다양한 방법으로 볼륨 관계를 관리할 수 있습니다.

*  replication
*  the mode of replication
*  a volume pair
*  a cluster pair




=== 복제를 일시 중지합니다

볼륨 쌍 속성을 편집하여 복제를 수동으로 일시 중지할 수 있습니다.

.단계
. NetApp Element 관리 * > * 보호 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Volume Pairs * 하위 탭을 선택합니다.
. 편집할 볼륨 쌍의 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 편집 * 을 선택합니다.
. 복제 프로세스를 수동으로 일시 중지하거나 시작합니다.
+

IMPORTANT: 볼륨 복제를 수동으로 일시 중지하거나 다시 시작하면 데이터 전송이 중단되거나 다시 시작됩니다. 두 사이트에서 이러한 변경 내용을 조정했는지 확인합니다.

. 변경 내용 저장 * 을 선택합니다.




=== 복제 모드를 변경합니다

볼륨 쌍 속성을 편집하여 볼륨 쌍 관계의 복제 모드를 변경할 수 있습니다.

.단계
. NetApp Element 관리 * > * 보호 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Volume Pairs * 하위 탭을 선택합니다.
. 편집할 볼륨 쌍의 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 편집 * 을 선택합니다.
. 새 복제 모드 선택:
+

IMPORTANT: 복제 모드를 변경하면 모드가 즉시 변경됩니다. 두 사이트에서 이러한 변경 내용을 조정했는지 확인합니다.

+
** * 실시간(동기식) *: 쓰기가 소스 및 타겟 클러스터 모두에서 커밋된 후 클라이언트에 인식됩니다.
** * 실시간(비동기식) *: 소스 클러스터에서 커밋된 쓰기가 클라이언트에 확인됩니다.
** * 스냅샷만 *: 소스 클러스터에서 생성된 스냅샷만 복제됩니다. 소스 볼륨의 활성 쓰기는 복제되지 않습니다.


. 변경 내용 저장 * 을 선택합니다.




=== 볼륨 쌍을 삭제합니다

두 볼륨 간의 쌍 연결을 제거하려면 볼륨 쌍을 삭제할 수 있습니다.

이 절차에서는 로컬 및 원격 사이트에서 vCenter를 사용하여 두 볼륨 간의 볼륨 페어링 관계를 삭제하는 방법에 대해 설명합니다.

vCenter 플러그인에서 제어하지 않는 볼륨의 경우 또는 를 사용할 수 있습니다 link:https://docs.netapp.com/us-en/element-software/storage/task_replication_delete_volume_relationship_after_replication.html["볼륨 쌍의 끝을 삭제합니다"] Element 웹 UI 사용

.단계
. NetApp Element 관리 * > * 보호 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Volume Pairs * 하위 탭을 선택합니다.
. 삭제할 볼륨 쌍을 하나 이상 선택합니다.
. 작업 * 을 선택합니다.
. 삭제 * 를 선택합니다.
. 각 볼륨 쌍의 세부 정보를 확인합니다.
+

NOTE: 플러그인이 관리하지 않는 클러스터의 경우 이 작업은 로컬 클러스터에서 볼륨 페어의 끝만 삭제합니다. 페어링 관계를 완전히 제거하려면 원격 클러스터에서 볼륨 쌍 끝을 수동으로 삭제해야 합니다.

. (플러그인으로 관리되는 클러스터의 경우 선택 사항) * 복제 타겟 액세스 변경 * 확인란을 선택하고 복제 타겟 볼륨의 새 액세스 모드를 선택합니다. 이 새로운 액세스 모드는 볼륨 페어링 관계가 제거된 후에 적용됩니다.
. 예 * 를 선택합니다.




=== 클러스터 쌍을 삭제합니다

로컬 사이트와 원격 사이트의 vCenter를 사용하여 두 클러스터 간의 클러스터 페어링 관계를 삭제할 수 있습니다. 클러스터 페어링 관계를 완전히 제거하려면 로컬 및 원격 클러스터 모두에서 클러스터 쌍 끝을 제거해야 합니다.

vCenter 플러그인을 사용하여 클러스터 쌍 끝을 삭제할 수 있습니다

vCenter 플러그인으로 제어되지 않는 클러스터의 경우 또는 를 사용할 수 있습니다 link:https://docs.netapp.com/us-en/element-software/storage/task_replication_delete_cluster_pair.html["클러스터 쌍 끝을 삭제합니다"] Element 웹 UI 사용

.단계
. NetApp Element 관리 * > * 보호 * 를 선택합니다.
. Cluster Pairs * 하위 탭을 선택합니다.
. 삭제할 클러스터 쌍의 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 삭제 * 를 선택합니다.
. 작업을 확인합니다.
+

NOTE: 이 작업을 수행하면 로컬 클러스터에서 클러스터 쌍만 삭제됩니다. 페어링 관계를 완전히 제거하려면 원격 클러스터에서 클러스터 쌍 끝을 수동으로 삭제해야 합니다.

. 클러스터 페어링에서 원격 클러스터의 단계를 반복합니다.




== 볼륨 페어링 메시지 및 경고

NetApp Element 관리 구성 지점에서 보호 탭의 볼륨 쌍 페이지에서 페어링되었거나 페어링 진행 중인 볼륨에 대한 정보를 볼 수 있습니다.

볼륨 상태 열에 페어링 및 진행 메시지가 표시됩니다.

*  pairing messages
*  pairing warnings




=== 볼륨 페어링 메시지

NetApp Element 관리 구성 지점에서 보호 탭의 볼륨 쌍 페이지에서 초기 페어링 프로세스 중에 메시지를 볼 수 있습니다. 이러한 메시지는 볼륨 상태 열에 표시되며 페어링의 소스 및 대상 끝 모두에 표시될 수 있습니다.

* * PausedDisconnected *: 소스 복제 또는 동기화 RPC 시간이 초과되었습니다. 원격 클러스터에 대한 연결이 끊어졌습니다. 클러스터에 대한 네트워크 연결을 확인합니다.
* * ResumingConnected**: 이제 원격 복제 동기화가 활성화됩니다. 동기화 프로세스를 시작하고 데이터를 기다리는 중입니다.
* * ResumingRSync**: 볼륨 메타데이터의 단일 나선형 복사본이 페어링된 클러스터에 만들어집니다.
* * ResumingLocalSync**: 볼륨 메타데이터의 이중 나선형 복사본이 페어링된 클러스터에 만들어집니다.
* * ResumingDataTransfer**: 데이터 전송이 다시 시작되었습니다.
* * 활성 *: 볼륨이 페어링되고 데이터가 소스에서 타겟 볼륨으로 전송되고 데이터가 동기화됩니다.
* * 유휴 *: 복제 작업이 발생하지 않습니다.


* 이 프로세스는 타겟 볼륨에 의해 구동되며 소스 볼륨에 표시되지 않을 수 있습니다.



=== 볼륨 페어링 경고

NetApp Element 관리 구성 지점에서 보호 탭의 볼륨 쌍 페이지에서 볼륨을 페어링한 후 경고 메시지를 볼 수 있습니다. 이러한 메시지는 볼륨 상태 열에 표시되며 페어링의 소스 및 대상 끝 모두에 표시될 수 있습니다.

달리 명시되지 않는 한 이러한 메시지는 페어링의 소스 및 타겟 끝에 모두 표시될 수 있습니다.

* * PausedClusterFull *: 타겟 클러스터가 가득 차서 소스 복제 및 대량 데이터 전송을 계속할 수 없습니다. 메시지는 페어의 소스 끝에만 표시됩니다.
* * PausedExcededMaxSnapshotCount *: 타겟 볼륨에 이미 최대 수의 스냅샷이 있으며 추가 스냅샷을 복제할 수 없습니다.
* * PausedManual *: 로컬 볼륨이 수동으로 일시 중지되었습니다. 복제를 다시 시작하기 전에 일시 중지 해제되어야 합니다.
* * PausedManualRemote *: 원격 볼륨이 수동 일시 중지 모드에 있습니다. 복제를 다시 시작하기 전에 원격 볼륨의 일시 중지를 해제하는 데 수동 개입이 필요합니다.
* * PausedMisConfigured *: 활성 소스 및 타겟을 기다리는 중입니다. 복제를 다시 시작하려면 수동 작업이 필요합니다.
* * PausedQoS *: 타겟 QoS가 수신 IO를 유지할 수 없습니다. 복제가 자동으로 재개됩니다. 메시지는 페어의 소스 끝에만 표시됩니다.
* * PausedSlowLink *: 느린 링크가 감지되어 복제를 중지했습니다. 복제가 자동으로 재개됩니다. 메시지는 페어의 소스 끝에만 표시됩니다.
* * PausedVolumeSizeMismatch *: 타겟 볼륨이 소스 볼륨보다 작습니다.
* * PausedXCopy *: 소스 볼륨에 SCSI XCOPY 명령이 실행됩니다. 복제를 다시 시작하려면 명령을 완료해야 합니다. 메시지는 페어의 소스 끝에만 표시됩니다.
* * StoppedMisConfigured*: 영구적인 구성 오류가 감지되었습니다. 원격 볼륨이 제거되었거나 페어링되지 않았습니다. 수정 조치가 가능하지 않습니다. 새 페어링을 설정해야 합니다.




== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 문서"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]

