---
sidebar: sidebar 
permalink: vcp_task_reports_alerts.html 
summary: vCenter Server용 NetApp Element 플러그인의 보고 페이지를 사용하여 클러스터가 얼마나 잘 실행되고 있는지 나타내는 정보, 경고 또는 오류를 제공하는 알림을 모니터링합니다. 
keywords: netapp, hci, vcp, vcenter, element, monitor, report, alert, cluster, performance 
---
= 시스템 경고를 모니터링합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
클러스터의 실행 상태를 나타내는 정보, 경고 또는 오류와 같은 경고를 모니터링할 수 있습니다.

경고는 클러스터 장애 또는 오류이며 발생할 때 보고됩니다. 대부분의 오류는 자동으로 해결되지만 일부 오류에는 수동 개입이 필요할 수 있습니다. 시스템은 경고 페이지에 각 경고와 함께 경고 오류 코드를 보고합니다. 오류 코드를 사용하면 시스템에서 어떤 구성 요소가 경고를 발생했고 경고가 발생한 이유를 확인할 수 있습니다. 을 참조하십시오 link:vcp_reference_reports_alert_errors.html["시스템 알림 목록"] 을 참조하십시오.

문제를 해결한 후 시스템은 자체적으로 폴링하여 문제를 해결된 것으로 식별합니다. 그런 다음 해결된 날짜를 포함한 모든 경고 정보가 해결된 보기로 이동됩니다.

.단계
. vCenter 플러그인에서 * NetApp Element Management * 를 선택합니다.
. Reporting * > * Alerts * 를 선택합니다.
. 다음 클러스터 알림 정보를 모니터링합니다.
+
** * ID *: 클러스터 경고의 고유 ID입니다.
** * 심각도 *
+
*** * 경고 *: 곧 주의가 필요할 수 있는 사소한 문제입니다. 이 심각도 수준에서는 시스템 업그레이드가 계속 허용됩니다.
*** * 오류 *: 성능 저하 또는 고가용성(HA) 손실을 초래할 수 있는 장애입니다. 그렇지 않으면 오류는 서비스에 영향을 주지 않습니다.
*** * 심각 *: 서비스에 영향을 미치는 심각한 고장. 시스템에서 API 또는 클라이언트 I/O 요청을 처리할 수 없습니다. 이 상태에서 작동하면 데이터가 손실될 수 있습니다.
*** * 모범 사례 *: 권장되는 시스템 구성 모범 사례는 사용되지 않습니다.


** * 유형 *
+
*** * 노드 *: 전체 노드에 영향을 미치는 결함.
*** * 드라이브 *: 개별 드라이브에 영향을 주는 고장.
*** * 클러스터 *: 전체 클러스터에 영향을 주는 고장.
*** * 서비스 *: 클러스터의 서비스에 영향을 주는 고장.
*** * 볼륨 *: 클러스터의 볼륨에 영향을 주는 오류.


** * 노드 *: 이 결함이 참조하는 노드의 노드 ID입니다. 노드 및 드라이브 장애에 대해 포함되며, 그렇지 않을 경우 -(대시)로 설정됩니다.
** * 드라이브 ID *: 이 오류가 참조하는 드라이브의 드라이브 ID입니다. 드라이브 고장에 대해 포함되며, 그렇지 않으면 -(대시)로 설정됩니다.
** * 오류 코드*: 오류의 원인을 나타내는 설명 코드입니다.
** * 세부 정보 *: 결함에 대한 상세 설명.
** * 시간 *: 이 제목은 활성 필터 보기에서만 볼 수 있습니다. 고장이 기록된 날짜 및 시간입니다.
** * 해결 날짜 *: 이 제목은 해결된 필터 보기에서만 볼 수 있습니다. 고장이 해결된 날짜 및 시간입니다.


. 문제가 해결되었는지 확인하려면 해결 보기에서 확인합니다.


[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 문서"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]

