---
sidebar: sidebar 
permalink: vcp_task_datastores_manage.html 
summary: 플러그인을 사용하여 Element 볼륨에 생성된 관리 데이터 저장소를 추가할 수 있습니다. 
keywords: netapp, datastore, vcp, vcenter, element 
---
= 데이터 저장소를 관리합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Element Plug-in for VMware vCenter Server를 사용하여 Element 볼륨이 백업하는 데이터 저장소를 관리할 수 있습니다. 데이터 저장소를 생성, 확장, 클론 복제, 공유 또는 삭제할 수 있습니다. 또한 VAAI UNMAP을 사용하여 클러스터가 씬 프로비저닝된 VMFS 데이터 저장소에서 확보된 블록 공간을 재확보할 수 있습니다.

.필요한 것
* 데이터 저장소를 생성하고 관리하려면 먼저 사용자 계정을 하나 이상 생성해야 합니다.
* 데이터 저장소와 함께 QoSSIOC 서비스를 사용하려면 먼저 플러그인 확장 지점에서 QoSSIOC 설정 페이지의 설정을 구성해야 합니다.
+
** link:vcp_task_getstarted_5_0.html#configure-qossioc-settings-using-the-plug-in["Element vCenter 플러그인 5.0 이상을 사용하여 설정을 구성합니다"]
** link:vcp_task_getstarted.html#configure-qossioc-settings-using-the-plug-in["Element vCenter 플러그인 4.10 이하를 사용하여 설정을 구성합니다"]


* 선택한 ESXi 호스트에서 지원하는 가장 높은 VMFS 버전을 사용하여 데이터 저장소를 생성하므로 VMFS 호환성 문제를 방지하려면 모든 클러스터 구성원이 동일한 버전의 vSphere 및 ESXi를 실행해야 합니다.


.옵션
* <<데이터 저장소를 생성합니다>>
* <<데이터 저장소 목록을 봅니다>>
* <<데이터 저장소를 확장합니다>>
* <<데이터 저장소의 클론을 생성합니다>>
* <<데이터 저장소를 공유합니다>>
* <<VAAI UNMAP을 수행합니다>>
* <<데이터 저장소를 삭제합니다>>



TIP: vSphere에서 작업 모니터링을 사용하여 데이터 저장소 작업을 완료한 후 모니터링할 수 있습니다.



== 데이터 저장소를 생성합니다

플러그인 확장에서 데이터 저장소를 생성할 수 있습니다.

.필요한 것
* vCenter Server에 하나 이상의 호스트가 접속되어 있어야 합니다.
* 하나 이상의 클러스터를 추가하고 실행해야 합니다.
+

NOTE: vCenter 연결 모드를 사용하는 경우 올바른 vCenter Server에 클러스터를 추가했는지 확인합니다.

* 하나 이상의 사용자 계정을 만들어야 합니다.
* 데이터 저장소와 함께 QoSSIOC 서비스를 사용하려면 먼저 플러그인 확장 지점에서 QoSSIOC 설정 페이지의 설정을 구성해야 합니다.
+
** link:vcp_task_getstarted_5_0.html#configure-qossioc-settings-using-the-plug-in["Element vCenter Plug-in 5.0 이상을 사용하여 설정을 구성합니다"]
** link:vcp_task_getstarted.html#configure-qossioc-settings-using-the-plug-in["Element vCenter 플러그인 4.10 이하를 사용하여 설정을 구성합니다"]




.단계
. vSphere Web Client에서 * Management * 탭을 엽니다.
+
** Element vCenter 플러그인 5.0부터 * NetApp Element 원격 플러그인 > 관리 > 관리 * 를 선택합니다.
** Element vCenter 플러그인 4.10 및 이전 버전의 경우 * NetApp Element 관리 > 관리 * 를 선택합니다.


+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. Datastore 페이지에서 * Create Datastore * 를 선택합니다.
. 데이터 저장소의 이름을 입력합니다.
+

TIP: 데이터 센터의 각 데이터 저장소에 고유한 이름을 사용합니다. 여러 클러스터 또는 vCenter Server 환경의 경우 이름 지정 Best Practice를 참조하십시오.

. 다음 * 을 선택합니다.
. 데이터 저장소에 필요한 호스트를 하나 이상 선택합니다.
+

NOTE: 새 데이터 저장소를 생성하려면 접속된 호스트가 하나 이상 있어야 합니다. 호스트에 여러 이니시에이터가 있는 경우 이니시에이터 또는 호스트를 선택하여 모든 이니시에이터를 선택합니다. vCenter 연결 모드를 사용하는 경우 클러스터가 할당된 vCenter Server에서 사용할 수 있는 호스트만 선택할 수 있습니다.

. 다음 * 을 선택합니다.
. 볼륨 구성 * 창에서 기존 볼륨을 선택하고 다음 단계를 진행하거나 새 데이터 저장소에 대한 새 볼륨을 생성합니다.
+

NOTE: 기존 볼륨을 선택하여 새 데이터 저장소를 생성하면 기존 데이터가 손실됩니다. 기존 VMFS 볼륨에 대해서는 VMware 설명서를 참조하십시오 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EEFEB765-A41F-4B6D-917C-BB9ABB80FC80.html["VMFS 데이터 저장소 복제본 마운트"^] 및 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EBAB0D5A-3C77-4A9B-9884-3D4AD69E28DC.html["중복 VMFS 데이터 저장소 관리"^].

+
.. 데이터 저장소를 백업하는 볼륨의 이름을 입력합니다.
.. 계정 목록에서 사용자 계정을 선택합니다.
.. 생성할 볼륨의 총 크기를 입력합니다.
+

NOTE: 기본 볼륨 크기 선택은 GB입니다. GB 또는 GiB 단위로 측정된 크기를 사용하여 볼륨을 생성할 수 있습니다. 1GB = 1,000,000바이트 1GiB = 1 073 741 824바이트

+
기본적으로 512바이트 에뮬레이션은 모든 새 볼륨에 대해 ON으로 설정됩니다.

.. 서비스 품질 * 영역에서 다음 중 하나를 수행합니다.
+
... Policy * 에서 기존 QoS 정책을 선택합니다.
... 사용자 지정 설정 * 에서 IOPS에 대한 사용자 지정 최소, 최대 및 버스트 값을 설정하거나 기본 QoS 값을 사용합니다.
+

TIP: QoS 정책은 예를 들어, 거의 재부팅되지 않고 동일한 스토리지 액세스가 필요한 데이터베이스, 애플리케이션 또는 인프라 서버와 같은 서비스 환경에 가장 적합합니다. 맞춤형 QoSSIOC 자동화는 가상 데스크톱 또는 특수한 키오스크 유형의 VM과 같이 매일 또는 하루에 여러 번 재부팅, 전원 켜기 또는 전원 끄기와 같은 가벼운 사용 VM에 가장 적합합니다. QoSSIOC 자동화 및 QoS 정책을 함께 사용해서는 안 됩니다.

+

TIP: 최대 또는 버스트 IOPS 값이 20,000 IOPS 이상인 볼륨은 단일 볼륨에서 이러한 IOPS 수준을 달성하기 위해 큐 길이가 크거나 여러 세션이 필요할 수 있습니다.





. 다음 * 을 선택합니다.
. 다음 중 하나를 선택하여 호스트 액세스에 대한 인증 유형을 구성합니다.
+
** * 볼륨 액세스 그룹 사용 *: 볼륨을 볼 수 있는 이니시에이터를 명시적으로 제한하려면 선택합니다.
** * CHAP 사용 *: 초기자에 대한 제한 없이 보안 암호 기반 액세스를 위해 선택합니다.


. 다음 * 을 선택합니다.
. 볼륨 액세스 그룹 사용 * 을 선택한 경우 선택한 호스트에 대한 볼륨 액세스 그룹을 구성합니다.
+
선택한 이니시에이터에 필요한 * 에 나열된 볼륨 액세스 그룹은 이전 단계에서 선택한 호스트 이니시에이터 중 하나 이상에 이미 연결되어 있습니다

+
.. 사용 가능한 이니시에이터와 연결할 추가 볼륨 액세스 그룹을 선택하거나 새 볼륨 액세스 그룹을 생성합니다.
+
*** * 사용 가능 *: 클러스터의 다른 볼륨 액세스 그룹 옵션.
*** * 새 액세스 그룹 생성 *: 새 액세스 그룹의 이름을 입력하고 * 추가 * 를 선택합니다.


.. 다음 * 을 선택합니다.
.. 호스트 액세스 구성 * 창에서 사용 가능한 호스트 이니시에이터(IQN 또는 WWPN)를 이전 창에서 선택한 볼륨 액세스 그룹에 연결합니다. 호스트 이니시에이터가 이미 볼륨 액세스 그룹에 연결되어 있는 경우 필드는 해당 이니시에이터에 대해 읽기 전용입니다. 호스트 이니시에이터에 볼륨 액세스 그룹 연결이 없으면 이니시에이터 옆의 목록에서 옵션을 선택합니다.
.. 다음 * 을 선택합니다.


. QoSSIOC 자동화를 활성화하려면 * QoS 및 SIOC 사용 * 을 선택한 다음 QoSSIOC 설정을 구성합니다.
+
--

TIP: QoS 정책을 사용하는 경우 QoSSIOC를 활성화하지 마십시오. QoSSIOC는 볼륨 QoS 설정에 대한 QoS 값을 재정의하고 조정합니다.

QoSSIOC 서비스를 사용할 수 없는 경우 먼저 QoSSIOC 설정을 구성해야 합니다.

** link:vcp_task_getstarted_5_0.html#configure-qossioc-settings-using-the-plug-in["Element vCenter 플러그인 5.0 이상을 사용하여 설정을 구성합니다"]
** link:vcp_task_getstarted.html#configure-qossioc-settings-using-the-plug-in["Element vCenter 플러그인 4.10 이하를 사용하여 설정을 구성합니다"]


--
+
.. QoS 및 SIOC 사용 * 을 선택합니다.
.. 버스트 계수 * 를 구성합니다.
+

NOTE: 버스트 계수는 VMDK에 대한 IOPS 제한(SIOC) 설정의 배수입니다. 기본값을 변경하는 경우 버스트 인수 값에 VMDK에 대한 IOPS 제한을 곱할 때 요소 볼륨의 최대 버스트 제한을 초과하지 않는 버스트 비율 값을 사용해야 합니다.

.. (선택 사항) * 기본 QoS 재정의 * 를 선택하고 설정을 구성합니다.
+

NOTE: 데이터 저장소에 대해 Override Default QoS(기본 QoS 재정의) 설정을 비활성화하면 각 VM의 기본 SIOC 설정을 기반으로 공유 및 Limit IOPS 값이 자동으로 설정됩니다.

+

TIP: SIOC 공유 제한을 사용자 지정하지 않고 SIOC 공유 제한을 사용자 지정하지 마십시오.

+

TIP: 기본적으로 최대 SIOC 디스크 공유는 '무제한'으로 설정됩니다. VDI와 같은 대규모 VM 환경에서는 클러스터의 최대 IOPS가 오버 커밋될 수 있습니다. QoSSIOC를 활성화할 때는 항상 기본 QoS 재정의 를 선택하고 IOPS 제한 옵션을 적절한 값으로 설정하십시오.



. 다음 * 을 선택합니다.
. 선택 사항을 확인하고 * Finish * 를 클릭합니다.
. 작업의 진행률을 보려면 vSphere에서 작업 모니터링을 사용하십시오. 데이터 저장소가 목록에 나타나지 않으면 보기를 새로 고칩니다.




== 데이터 저장소 목록을 봅니다

플러그인 확장 지점에서 데이터 저장소 페이지에서 사용 가능한 데이터 저장소를 볼 수 있습니다.

. vSphere Web Client에서 * Management * 탭을 엽니다.
+
** Element vCenter 플러그인 5.0부터 * NetApp Element 원격 플러그인 > 관리 > 관리 * 를 선택합니다.
** Element vCenter 플러그인 4.10 및 이전 버전의 경우 * NetApp Element 관리 > 관리 * 를 선택합니다.


+

NOTE: 둘 이상의 클러스터가 추가된 경우 탐색 모음에서 사용할 클러스터를 선택합니다.

. 데이터 저장소 목록을 검토합니다.
+

NOTE: 여러 볼륨(혼합 데이터 저장소)에 걸쳐 있는 데이터 저장소가 표시되지 않습니다. 데이터 저장소 보기에는 선택한 NetApp Element 클러스터의 ESXi 호스트에서 사용할 수 있는 데이터 저장소만 표시됩니다.

. 다음 정보를 검토하십시오.
+
** * Name *: 데이터 저장소에 할당된 이름입니다.
** * 호스트 이름 *: 연결된 각 호스트 장치의 주소입니다.
** * Status *: 가능한 값 "Accessible" 또는 "Inaccessible"은 데이터 저장소가 현재 vSphere에 연결되어 있는지 여부를 나타냅니다.
** * Type *: VMware 파일 시스템 데이터 저장소 유형입니다.
** * 볼륨 이름 *: 연결된 볼륨에 할당된 이름입니다.
** * 볼륨 NAA *: NAA IEEE 등록 확장 형식으로 연결된 볼륨에 대한 전역적으로 고유한 SCSI 장치 식별자입니다.
** * 총 용량(GB) *: 데이터 저장소의 총 포맷 용량입니다.
** * 여유 용량(GB) *: 데이터 저장소에 사용할 수 있는 공간입니다.
** * QoSSIOC 자동화 *: QoSSIOC 자동화가 활성화되었는지 여부를 나타냅니다. 가능한 값:
+
*** '활성화됨': QoSSIOC가 활성화됩니다.
*** "사용 안 함": QoSSIOC가 활성화되지 않았습니다.
*** Max exceeded: Volume Max QoS가 지정된 제한 값을 초과했습니다.








== 데이터 저장소를 확장합니다

플러그인 확장 지점을 사용하여 데이터 저장소를 확장하여 볼륨 크기를 늘릴 수 있습니다. 데이터 저장소를 확장하면 해당 데이터 저장소와 관련된 VMFS 볼륨도 확장됩니다.

.단계
. vSphere Web Client에서 * Management * 탭을 엽니다.
+
** Element vCenter 플러그인 5.0부터 * NetApp Element 원격 플러그인 > 관리 > 관리 * 를 선택합니다.
** Element vCenter 플러그인 4.10 및 이전 버전의 경우 * NetApp Element 관리 > 관리 * 를 선택합니다.


+

NOTE: 둘 이상의 클러스터가 추가된 경우 탐색 모음에서 사용할 클러스터를 선택합니다.

. Datastores 페이지에서 확장할 데이터 저장소에 대한 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 결과 메뉴에서 * Extend * 를 선택합니다.
. New Datastore Size 필드에 새 데이터 저장소에 필요한 크기를 입력하고 GB 또는 GiB를 선택합니다.
+

NOTE: 데이터 저장소를 확장하면 전체 볼륨의 크기가 사용됩니다. 새 데이터 저장소 크기는 선택한 클러스터에서 사용할 수 있는 프로비저닝되지 않은 공간 또는 클러스터에서 허용하는 최대 볼륨 크기를 초과할 수 없습니다.

. OK * 를 선택합니다.
. 페이지를 새로 고칩니다.




== 데이터 저장소의 클론을 생성합니다

새 데이터 저장소를 원하는 ESXi 서버 또는 클러스터에 마운트하는 플러그인이 포함된 데이터 저장소를 클론할 수 있습니다. 데이터 저장소 클론의 이름을 지정하고 QoSSIOC, 볼륨, 호스트 및 권한 부여 유형 설정을 구성할 수 있습니다.

소스 데이터 저장소에 가상 머신이 있는 경우 클론 데이터 저장소의 가상 머신이 새 이름으로 인벤토리로 들어갑니다.

클론 데이터 저장소의 볼륨 크기는 소스 데이터 저장소를 백업하는 볼륨의 크기와 일치합니다. 기본적으로 512바이트 에뮬레이션은 모든 새 볼륨에 대해 ON으로 설정됩니다.

.필요한 것
* vCenter Server에 하나 이상의 호스트가 접속되어 있어야 합니다.
* 하나 이상의 클러스터를 추가하고 실행해야 합니다.
+

NOTE: vCenter 연결 모드를 사용하는 경우 올바른 vCenter Server에 클러스터를 추가했는지 확인합니다.

* 프로비저닝되지 않은 사용 가능한 공간은 소스 볼륨 크기보다 크거나 같아야 합니다.
* 하나 이상의 사용자 계정을 만들어야 합니다.


.단계
. vSphere Web Client에서 * Management * 탭을 엽니다.
+
** Element vCenter 플러그인 5.0부터 * NetApp Element 원격 플러그인 > 관리 > 관리 * 를 선택합니다.
** Element vCenter 플러그인 4.10 및 이전 버전의 경우 * NetApp Element 관리 > 관리 * 를 선택합니다.


+

NOTE: 둘 이상의 클러스터가 추가된 경우 탐색 모음에서 사용할 클러스터를 선택합니다.

. Datastores * 페이지에서 복제할 데이터 저장소의 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 결과 메뉴에서 * Clone * 을 선택합니다.
+

NOTE: 연결된 디스크가 있는 가상 머신이 포함된 데이터 저장소를 선택한 데이터 저장소에 복제하려고 하면 복제된 데이터 저장소에 있는 가상 머신의 복제본이 가상 머신 인벤토리에 추가되지 않습니다.

. 데이터 저장소 이름을 입력합니다.
+

TIP: 데이터 센터의 각 데이터 저장소에 고유한 이름을 사용합니다. 여러 클러스터 또는 vCenter Server 환경의 경우 이름 지정 Best Practice를 참조하십시오.

. 다음 * 을 선택합니다.
. 데이터 저장소에 필요한 호스트를 하나 이상 선택합니다.
+

NOTE: 새 데이터 저장소를 생성하려면 접속된 호스트가 하나 이상 있어야 합니다. 호스트에 여러 이니시에이터가 있는 경우 이니시에이터 또는 호스트를 선택하여 모든 이니시에이터를 선택합니다. vCenter 연결 모드를 사용하는 경우 클러스터가 할당된 vCenter Server에서 사용할 수 있는 호스트만 선택할 수 있습니다.

. 다음 * 을 선택합니다.
. 볼륨 구성 * 창에서 다음을 수행합니다.
+
.. 클론 데이터 저장소를 백업하는 새 NetApp Element 볼륨의 이름을 입력합니다.
.. 계정 목록에서 사용자 계정을 선택합니다.
+

NOTE: 볼륨을 생성하려면 기존 사용자 계정이 하나 이상 있어야 합니다.

.. 서비스 품질 * 영역에서 다음 중 하나를 수행합니다.
+
*** 정책 * 에서 기존 QoS 정책을 선택합니다(사용 가능한 경우).
*** 사용자 지정 설정 * 에서 IOPS에 대한 사용자 지정 최소, 최대 및 버스트 값을 설정하거나 기본 QoS 값을 사용합니다.
+

TIP: QoS 정책은 예를 들어, 거의 재부팅되지 않고 동일한 스토리지 액세스가 필요한 데이터베이스, 애플리케이션 또는 인프라 서버와 같은 서비스 환경에 가장 적합합니다. 맞춤형 QoSSIOC 자동화는 가상 데스크톱 또는 특수한 키오스크 유형의 VM과 같이 매일 또는 하루에 여러 번 재부팅, 전원 켜기 또는 전원 끄기와 같은 가벼운 사용 VM에 가장 적합합니다. QoSSIOC 자동화 및 QoS 정책을 함께 사용해서는 안 됩니다.

+

TIP: 최대 또는 버스트 IOPS 값이 20,000 IOPS 이상인 볼륨은 단일 볼륨에서 이러한 IOPS 수준을 달성하기 위해 큐 길이가 크거나 여러 세션이 필요할 수 있습니다.





. 다음 * 을 선택합니다.
. 다음 옵션 중 하나를 선택하여 호스트 액세스에 대한 인증 유형을 구성합니다.
+
** * 볼륨 액세스 그룹 사용 *: 볼륨을 볼 수 있는 이니시에이터를 명시적으로 제한하려면 선택합니다.
** * CHAP 사용 *: 초기자에 대한 제한 없이 보안 암호 기반 액세스를 위해 선택합니다.


. 다음 * 을 선택합니다.
. 볼륨 액세스 그룹 사용 * 을 선택한 경우 선택한 호스트에 대한 볼륨 액세스 그룹을 구성합니다.
+
선택한 이니시에이터에 필요한 * 에 나열된 볼륨 액세스 그룹은 이전 단계에서 선택한 호스트 이니시에이터 중 하나 이상에 이미 연결되어 있습니다.

+
.. 사용 가능한 이니시에이터와 연결할 추가 볼륨 액세스 그룹을 선택하거나 새 볼륨 액세스 그룹을 생성합니다.
+
*** * 사용 가능 *: 클러스터의 다른 볼륨 액세스 그룹 옵션.
*** * 새 액세스 그룹 생성 *: 새 액세스 그룹의 이름을 입력하고 * 추가 * 를 클릭합니다.


.. 다음 * 을 선택합니다.
.. 호스트 액세스 구성 * 창에서 사용 가능한 호스트 이니시에이터(IQN 또는 WWPN)를 이전 창에서 선택한 볼륨 액세스 그룹에 연결합니다.
+
호스트 이니시에이터가 이미 볼륨 액세스 그룹에 연결되어 있는 경우 필드는 해당 이니시에이터에 대해 읽기 전용입니다. 호스트 이니시에이터에 볼륨 액세스 그룹 연결이 없으면 이니시에이터 옆의 드롭다운 목록에서 옵션을 선택합니다.

.. 다음 * 을 선택합니다.


. QoSSIOC 자동화를 활성화하려면 * QoS 및 SIOC 사용 * 상자를 선택한 다음 QoSSIOC 설정을 구성합니다.
+
--

IMPORTANT: QoS 정책을 사용하는 경우 QoSSIOC를 활성화하지 마십시오. QoSSIOC는 볼륨 QoS 설정에 대한 QoS 값을 재정의하고 조정합니다.

QoSSIOC 서비스를 사용할 수 없는 경우 먼저 플러그인 확장 지점에서 QoSSIOC 설정 페이지에서 설정을 구성해야 합니다.

** link:vcp_task_getstarted_5_0.html#configure-qossioc-settings-using-the-plug-in["Element vCenter 플러그인 5.0 이상을 사용하여 설정을 구성합니다"]
** link:vcp_task_getstarted.html#configure-qossioc-settings-using-the-plug-in["Element vCenter 플러그인 4.10 이하를 사용하여 설정을 구성합니다"]


--
+
.. QoS 및 SIOC 사용 * 을 선택합니다.
.. 버스트 계수 * 를 구성합니다.
+

NOTE: 버스트 계수는 VMDK에 대한 IOPS 제한(SIOC) 설정의 배수입니다. 기본값을 변경하는 경우 버스트 비율 값에 VMDK에 대한 IOPS 제한을 곱할 때 NetApp Element 볼륨의 최대 버스트 제한을 초과하지 않는 버스트 비율 값을 사용해야 합니다.

.. * 선택 사항 *: * 기본 QoS 재정의 * 를 선택하고 설정을 구성합니다.
+
데이터 저장소에 대해 Override Default QoS(기본 QoS 재정의) 설정을 비활성화하면 각 VM의 기본 SIOC 설정을 기반으로 공유 및 Limit IOPS 값이 자동으로 설정됩니다.

+

TIP: SIOC 공유 제한을 사용자 지정하지 않고 SIOC 공유 제한을 사용자 지정하지 마십시오.

+

TIP: 기본적으로 최대 SIOC 디스크 공유는 '무제한'으로 설정됩니다. VDI와 같은 대규모 VM 환경에서는 클러스터의 최대 IOPS가 오버 커밋될 수 있습니다. QoSSIOC를 활성화할 때는 항상 기본 QoS 재정의 를 선택하고 IOPS 제한 옵션을 적절한 값으로 설정하십시오.



. 다음 * 을 선택합니다.
. 선택 사항을 확인하고 * Finish * 를 선택합니다.
. 페이지를 새로 고칩니다.




== 데이터 저장소를 공유합니다

플러그인 확장 지점을 사용하여 하나 이상의 호스트와 데이터 저장소를 공유할 수 있습니다.

데이터 저장소는 동일한 데이터 센터 내의 호스트 사이에서만 공유할 수 있습니다.

.필요한 것
* 하나 이상의 클러스터를 추가하고 실행해야 합니다.
+

NOTE: vCenter 연결 모드를 사용하는 경우 올바른 vCenter Server에 클러스터를 추가했는지 확인합니다.

* 선택한 데이터 센터 아래에 둘 이상의 호스트가 있어야 합니다.


.단계
. vSphere Web Client에서 * Management * 탭을 엽니다.
+
** Element vCenter 플러그인 5.0부터 * NetApp Element 원격 플러그인 > 관리 > 관리 * 를 선택합니다.
** Element vCenter 플러그인 4.10 및 이전 버전의 경우 * NetApp Element 관리 > 관리 * 를 선택합니다.


+

NOTE: 둘 이상의 클러스터가 추가된 경우 탐색 모음에서 사용할 클러스터를 선택합니다.

. Datastores * 페이지에서 공유할 데이터 저장소의 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 결과 메뉴에서 * 공유 * 를 선택합니다.
. 다음 옵션 중 하나를 선택하여 호스트 액세스에 대한 인증 유형을 구성합니다.
+
** * 볼륨 액세스 그룹 사용 *: 볼륨을 볼 수 있는 이니시에이터를 명시적으로 제한하려면 이 옵션을 선택합니다.
** * CHAP 사용 *: 초기자에 대한 제한 없이 보안 암호 기반 액세스를 사용하려면 이 옵션을 선택합니다.


. 다음 * 을 선택합니다.
. 데이터 저장소에 필요한 호스트를 하나 이상 선택합니다.
+

NOTE: 새 데이터 저장소를 생성하려면 접속된 호스트가 하나 이상 있어야 합니다. 호스트에 여러 이니시에이터가 있는 경우 호스트를 선택하여 이니시에이터 또는 모든 이니시에이터를 선택합니다. vCenter 연결 모드를 사용하는 경우 클러스터가 할당된 vCenter Server에서 사용할 수 있는 호스트만 선택할 수 있습니다.

. 다음 * 을 선택합니다.
. 볼륨 액세스 그룹 * 사용을 선택한 경우 선택한 호스트에 대한 볼륨 액세스 그룹을 구성합니다.
+
선택한 이니시에이터에 필요한 * 에 나열된 볼륨 액세스 그룹은 이전 단계에서 선택한 호스트 이니시에이터 중 하나 이상에 이미 연결되어 있습니다.

+
.. 사용 가능한 이니시에이터와 연결할 추가 볼륨 액세스 그룹을 선택하거나 새 볼륨 액세스 그룹을 생성합니다.
+
*** * 사용 가능 *: 클러스터의 다른 볼륨 액세스 그룹 옵션.
*** * 새 액세스 그룹 생성 *: 새 액세스 그룹의 이름을 입력하고 * 추가 * 를 클릭합니다.


.. 다음 * 을 선택합니다.
.. 호스트 액세스 구성 * 창에서 사용 가능한 호스트 이니시에이터(IQN 또는 WWPN)를 이전 창에서 선택한 볼륨 액세스 그룹에 연결합니다.
+
호스트 이니시에이터가 이미 볼륨 액세스 그룹에 연결되어 있는 경우 필드는 해당 이니시에이터에 대해 읽기 전용입니다. 호스트 이니시에이터에 볼륨 액세스 그룹 연결이 없으면 이니시에이터 옆의 드롭다운 목록에서 옵션을 선택합니다.



. 선택 사항을 확인하고 * Finish * 를 선택합니다.
. 페이지를 새로 고칩니다.




== VAAI UNMAP을 수행합니다

클러스터가 씬 프로비저닝된 VMFS5 데이터 저장소에서 확보된 블록 공간을 재확보하도록 하려면 VAAI UNMAP 기능을 사용합니다.

.필요한 것
* 작업에 사용 중인 데이터 저장소가 VMFS5 이전인지 확인합니다. ESXi가 작업을 자동으로 수행하기 때문에 VAAI UNMAP을 VMFS6에 사용할 수 없습니다
* ESXi 호스트 시스템 설정이 VAAI UNMAP에 대해 설정되었는지 확인합니다.
+
"esxcli system settings advanced list -o/VMFS3/EnableBlockDelete"를 참조하십시오

+
활성화하려면 정수 값을 1로 설정해야 합니다.

* ESXi 호스트 시스템 설정이 VAAI UNMAP에 대해 설정되지 않은 경우 다음 명령을 사용하여 정수 값을 1로 설정합니다.
+
"esxcli system settings advanced set-i 1-o/VMFS3/EnableBlockDelete"



.단계
. vSphere Web Client에서 * Management * 탭을 엽니다.
+
** Element vCenter 플러그인 5.0부터 * NetApp Element 원격 플러그인 > 관리 > 관리 * 를 선택합니다.
** Element vCenter 플러그인 4.10 및 이전 버전의 경우 * NetApp Element 관리 > 관리 * 를 선택합니다.


+

NOTE: 둘 이상의 클러스터가 추가된 경우 탐색 모음에서 사용할 클러스터를 선택합니다.

. Datastores * 페이지에서 VAAI UNMAP을 사용할 데이터 저장소의 확인란을 선택합니다.
. 결과 메뉴에서 * Actions * 를 선택합니다.
. VAAI Unmap * 을 선택합니다.
. 이름 또는 IP 주소로 호스트를 선택합니다.
. 호스트 사용자 이름과 암호를 입력합니다.
. 선택 사항을 확인하고 * OK * 를 선택합니다.




== 데이터 저장소를 삭제합니다

플러그인 확장 지점을 사용하여 데이터 저장소를 삭제할 수 있습니다. 이 작업을 수행하면 삭제할 데이터 저장소의 VM과 연결된 모든 파일이 영구적으로 삭제됩니다. 플러그인은 등록된 VM이 포함된 데이터 저장소를 삭제하지 않습니다.

. vSphere Web Client에서 * Management * 탭을 엽니다.
+
** Element vCenter 플러그인 5.0부터 * NetApp Element 원격 플러그인 > 관리 > 관리 * 를 선택합니다.
** Element vCenter 플러그인 4.10 및 이전 버전의 경우 * NetApp Element 관리 > 관리 * 를 선택합니다.


+

NOTE: 둘 이상의 클러스터가 추가된 경우 탐색 모음에서 사용할 클러스터를 선택합니다.

. datastores * 페이지에서 삭제할 데이터 저장소의 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 결과 메뉴에서 * 삭제 * 를 선택합니다.
. (선택 사항) 데이터 저장소와 연결된 NetApp Element 볼륨을 삭제하려면 * Delete associated volume * (연결된 볼륨 삭제 *) 확인란을 선택합니다.
+

NOTE: 볼륨을 유지하고 나중에 다른 데이터 저장소에 연결하도록 선택할 수도 있습니다.

. 예 * 를 선택합니다.




== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 문서"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]

