---
sidebar: sidebar 
permalink: vcp_reference_troubleshoot_vcp.html 
summary: 플러그인과 관련된 몇 가지 일반적인 문제 및 해결 단계에 대해 알아볼 수 있습니다. 
keywords: netapp, hci, vcp, vcenter, element, troubleshoot, monitor, report, alert, cluster, performance 
---
= vCenter 플러그인 문제를 해결합니다
:hardbreaks:
:allow-uri-read: 
:url-peak: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Plug-in_for_vCenter_server/mNode_Status_shows_as_'Network_Down'_or_'Down'_in_the_mNode_Settings_tab_of_the_Element_Plugin_for_vCenter_(VCP)
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: media/


[role="lead"]
vCenter Server용 NetApp Element 플러그인과 관련된 몇 가지 일반적인 문제와 이러한 문제를 해결하는 단계를 알고 있어야 합니다.

* <<Plug-in registration successful but icons do not appear in web client>>
* <<Errors after NetApp Element Plug-in for vCenter Server 4.8 or later upgrade with VMware vCenter Server 6.7U1>>
* <<Error registering plug-in using Registration UI>>
* <<Error updating plug-in using Registration UI>>
* <<Error message that NetApp extension cannot be upgraded>>
* <<Removing plug-in completes successfully but icons remain>>
* <<Plug-in cannot be unregistered or removed after admin password change>>
* <<Plug-in management tasks fail or volumes are not accessible to ESXi host>>
* <<Failure occurs during vCenter Plug-in use on Firefox 59.0.2 browsers>>
* <<Delete datastore operation fails>>
* <<Cluster pair cannot connect using a pairing key>>
* <<Error message for QoSSIOC status>>
* <<QoSSIOC service shown as available but is unavailable>>
* <<QoSSIOC is enabled for datastore but unavailable>>




== 플러그인 등록에 성공했지만 웹 클라이언트에 아이콘이 표시되지 않습니다

등록이 성공한 것으로 표시되지만 vSphere Web Client에서 플러그인 아이콘이 표시되지 않습니다.

.수정 조치
* vSphere Web Client에서 로그아웃하고 다시 로그인합니다. 브라우저를 닫고 다시 열어야 할 수 있습니다.
* 브라우저 캐시를 지웁니다.
* vCenter에서 Windows 관리 도구의 서비스 메뉴에서 vSphere Web Client Service를 다시 시작하거나 vCenter를 재부팅합니다.
* vCenter 관리자 역할과 관련된 모든 필수 기본 관리 권한이 있는지 확인합니다.
* 플러그인 ZIP 파일이 vCenter에 다운로드되었는지 확인합니다.
+
.. vCenter에서 "vSphere_client_Virgo.log"를 엽니다. 버전 6.5 및 6.7용 vCenter 로그 파일은 다음 위치에 있습니다.
+
*** 플래시 설치: '/var/log/vmware/vsphere-client/logs/vsphere_client_Virgo.log'
*** HTML5 설치: `/var/log/vmware/vsphere-ui/logs/vsphere_client_Virgo.log'


.. ZIP 다운로드에 실패했다는 오류 메시지가 나타나면 ZIP을 다시 다운로드하십시오.
+

NOTE: 연결할 수 없거나 잘못된 URL을 수정해야 할 수 있습니다. 플러그인 등록을 업데이트하거나 등록을 취소하고 수정된 URL로 플러그인을 다시 등록합니다. "allowHTTP" 설정을 변경하지 않고 HTTP URL을 지정한 경우에도 ZIP을 다운로드하지 못할 수 있습니다.



* 네트워킹 포트를 확인합니다. 필요한 포트에서 vCenter에서 양방향 방식으로 관리 노드에 연결할 수 있는지 확인합니다.
* vCenter의 MOB 확장 레코드를 확인합니다 (https://<vcenterIP>/mob/?moid=ExtensionManager&doPath=extensionList["com.solidfire를 참조하십시오"]플러그인 ZIP의 다운로드 위치 URL이 포함된 .server:
+
.. 브라우저에 URL을 붙여 넣습니다.
.. 플러그인 ZIP을 다운로드할 수 있는지 확인합니다.
+
*** 플러그인 ZIP을 다운로드할 수 있는 경우 다음 단계를 진행하십시오.
*** 플러그인 ZIP을 다운로드할 수 없는 경우 vCenter Server와 관리 노드 간의 네트워킹 문제를 확인합니다.


.. 플러그인을 다운로드할 수 없는 경우 MOB 레코드의 'serverThumbprint'를 브라우저에 표시된 ZIP URL의 인증서 SHA-1과 비교합니다.
+
... MOB의 등록 레코드에 올바르지 않거나 오래된 URL 또는 SHA-1이 있는 경우 플러그 인을 등록 취소하고 플러그인을 다시 등록합니다.
... 문제가 지속되고 ZIP에 도달할 수 없는 경우 ZIP URL을 검사하여 사용된 관리 노드 주소에 문제가 있는지 확인합니다. 경우에 따라 ZIP 파일을 다운로드할 수 있도록 플러그인의 등록 유틸리티를 사용하여 URL을 사용자 지정해야 할 수도 있습니다.








== VMware vCenter Server 6.7U1을 사용하여 vCenter Server 4.8 이상 업그레이드용 NetApp Element 플러그인 후 오류가 발생했습니다

VMware vCenter Server 6.7U1을 사용하여 vCenter Server 4.8 이상용 NetApp Element 플러그인으로 업그레이드한 후 다음과 같은 문제가 발생할 수 있습니다.

* 클러스터는 * 클러스터 * 섹션에 나열되지 않습니다.
* NetApp Element 구성의 * 클러스터 및 QoSSIOC 설정 * 섹션에 서버 오류가 표시됩니다.


클러스터 및 QoSSIOC 설정을 복원합니다.

. vCenter에서 로그아웃합니다.
. 로그아웃한 후 3-5분 정도 기다린 다음 다시 로그인합니다.
. 현재 vSphere Client 보기에서 새로 고침 아이콘을 선택합니다.
. 예를 들어 Ctrl+F5를 사용하여 캐시를 해제하고 브라우저를 새로 고칩니다.
. 클러스터 및 QoSSIOC 설정이 복원되는지 확인합니다.
+
문제가 지속되면 다음을 수행해야 합니다 link:https://docs.netapp.com/us-en/vcp/vcp_task_getstarted.html#add-storage-clusters-for-use-with-the-plug-in["클러스터를 다시 추가합니다"^].





== 등록 UI를 사용하여 플러그인을 등록하는 동안 오류가 발생했습니다

등록 유틸리티를 사용할 때 vCenter Server에 플러그인을 등록하는 동안 오류가 발생했습니다. com.solidfire 키가 이미 설치되어 있습니다.

등록 유틸리티에서 * 플러그인 등록 * 대신 * 플러그인 업데이트 * 를 사용합니다.



== 등록 UI를 사용하여 플러그인을 업데이트하는 동안 오류가 발생했습니다

등록 유틸리티를 사용할 때 vCenter Server에 대한 플러그인을 업데이트하는 동안 오류가 발생했습니다. 이 업데이트에 대해 "com.solidfire" 키가 있는 플러그인이 설치되어 있지 않습니다.

등록 유틸리티에서 * 플러그인 업데이트 * 대신 * 플러그인 등록 * 을 사용합니다.



== NetApp 확장을 업그레이드할 수 없다는 오류 메시지가 나타납니다

.메시지
[listing]
----
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Could not open connection.
----
Windows vCenter Server를 버전 6.0에서 6.5로 업그레이드하는 동안 NetApp Extension을 업그레이드할 수 없거나 새 vCenter Server와 함께 사용할 수 없다는 경고가 표시됩니다. 업그레이드를 완료하고 vSphere Web Client에 로그인하면 vCenter 플러그인 확장 지점을 선택할 때 오류가 발생합니다. 이 오류는 런타임 데이터베이스를 저장하는 디렉터리가 버전 6.0에서 6.5로 변경되었기 때문에 발생합니다. vCenter 플러그인에서 런타임을 위해 필요한 파일을 생성할 수 없습니다.

.수정 조치
. 플러그 인 등록을 취소합니다.
. 플러그인 파일을 제거합니다.
. vCenter를 재부팅합니다.
. 플러그인을 등록합니다.
. vSphere Web Client에 로그인합니다.




== 플러그 인을 제거해도 성공적으로 완료되지만 아이콘은 유지됩니다

vCenter 플러그인 패키지 파일 제거가 성공적으로 완료되었지만 vSphere Web Client에서 플러그인 아이콘이 계속 표시됩니다.

vSphere Web Client에서 로그아웃하고 다시 로그인합니다. 브라우저를 닫았다가 다시 열어야 할 수 있습니다. vSphere Web Client에서 로그아웃해도 문제가 해결되지 않으면 vCenter Server 웹 서비스를 재부팅해야 할 수 있습니다. 또한 다른 사용자에게 기존 세션이 있을 수 있습니다. 모든 사용자 세션을 닫아야 합니다.



== 관리자 암호를 변경한 후에는 플러그인을 등록 취소 또는 제거할 수 없습니다

플러그인을 등록하는 데 사용된 vCenter의 관리자 암호가 변경된 후에는 vCenter 플러그인을 등록 또는 제거할 수 없습니다.

플러그인 2.6의 경우 vCenter 플러그인 * 등록 * / * 등록 해제 * 페이지로 이동합니다. vCenter IP 주소, 사용자 ID 및 암호를 변경하려면 * Update * 버튼을 클릭합니다.

플러그인 2.7 이상의 경우 플러그인의 mNode 설정에서 vCenter 관리자 암호를 업데이트합니다.

플러그인 4.4 이상의 경우 플러그인의 QoSSIOC 설정에서 vCenter 관리자 암호를 업데이트합니다.



== 플러그인 관리 작업이 실패하거나 ESXi 호스트에서 볼륨에 액세스할 수 없습니다

데이터 저장소 생성, 클론 생성 및 공유 작업이 실패하거나 ESXi 호스트에서 볼륨에 액세스할 수 없습니다.

.수정 조치
* 데이터 저장소 작업을 위해 ESXi 호스트에 소프트웨어 iSCSI HBA가 있고 활성화되어 있는지 확인합니다.
* 볼륨이 삭제되거나 잘못된 볼륨 액세스 그룹에 할당되지 않았는지 확인합니다.
* 볼륨 액세스 그룹에 올바른 호스트 IQN이 있는지 확인합니다.
* 연결된 계정에 올바른 CHAP 설정이 있는지 확인합니다.
* 볼륨 상태가 활성 상태이고 볼륨 액세스가 다시 쓰기이며 512e가 참으로 설정되어 있는지 확인합니다.




== Firefox 59.0.2 브라우저에서 vCenter 플러그인을 사용하는 동안 오류가 발생했습니다

"이름: HttpErrorResponse Raw 메시지: 에 대한 HTTP 실패 응답 https://vc6/ui/solidfire-war-4.2.0-SNAPSHOT/rest/vsphere//servers:[] 500 내부 서버 오류 반환 메시지: 서버 오류. 다시 시도하거나 NetApp Support에 문의하십시오

이 문제는 Firefox를 사용하는 vSphere HTML5 웹 클라이언트에서 발생합니다. vSphere Flash 클라이언트는 영향을 받지 않습니다.

브라우저 URL에서 전체 FQDN을 사용합니다. VMware는 IP, 짧은 이름 및 FQDN에 대한 전체 정방향 및 역방향 확인을 필요로 합니다.



== 데이터 저장소 삭제 작업이 실패했습니다

데이터 저장소 삭제 작업이 실패합니다.

모든 VM이 데이터 저장소에서 삭제되었는지 확인합니다. 데이터 저장소를 삭제하려면 먼저 데이터 저장소에서 VM을 삭제해야 합니다.



== 페어링 키를 사용하여 클러스터 쌍을 연결할 수 없습니다

페어링 키를 사용하여 클러스터를 페어링하는 동안 연결 오류가 발생합니다. 클러스터 페어링 생성 * 대화 상자의 오류 메시지는 호스트에 대한 경로가 없음을 나타냅니다.

구성되지 않은 클러스터 쌍을 로컬 클러스터에 생성한 프로세스를 수동으로 삭제하고 클러스터 페어링을 다시 수행하십시오.



== QoSSIOC 상태에 대한 오류 메시지입니다

플러그인의 QoSSIOC 상태는 경고 아이콘 및 오류 메시지를 표시합니다.

.수정 조치
* IP 주소에 연결할 수 없음: IP 주소가 유효하지 않거나 응답이 수신되지 않습니다. 주소가 올바른지, 관리 노드가 온라인 상태이고 사용 가능한지 확인합니다.
* 통신할 수 없음: IP 주소에 연결할 수 있지만 주소에 대한 호출은 실패합니다. 이는 QoSSIOC 서비스가 지정된 주소에서 실행되지 않거나 방화벽이 트래픽을 차단하고 있음을 나타낼 수 있습니다.
* SIOC 서비스에 연결할 수 없음: SIOC.LOG를 열고 관리 노드의 /OPT/solidfire/SIOC/DATA/LOG/("/var/log" 또는 이전 관리 노드의 '/var/log/solidfire/')에서 SIOC 서비스가 성공적으로 시작되었는지 확인합니다. SIOC 서비스를 시작하는 데 50초 이상 걸릴 수 있습니다. 서비스가 성공적으로 시작되지 않으면 다시 시도하십시오.




== QoSSIOC 서비스가 사용 가능으로 표시되지만 사용할 수 없습니다

QoSSIOC 서비스 설정이 UP로 표시되지만 QoSSIOC는 사용할 수 없습니다.

NetApp Element 구성 확장 포인트의 * QoSSIOC 설정 * 탭에서 새로 고침 버튼을 클릭합니다. 필요에 따라 IP 주소 또는 사용자 인증 정보를 업데이트합니다.



== QoSSIOC는 데이터 저장소에 대해 활성화되지만 사용할 수 없습니다

데이터 저장소에 QoSSIOC가 활성화되어 있지만 QoSSIOC는 사용할 수 없습니다.

VMware SIOC가 데이터 저장소에 설정되어 있는지 확인합니다.

. 관리 노드의 /opt/solidfire/sIOC/data/logs/'에서 'sIOC.log'를 엽니다('/var/log' 또는 이전 관리 노드의 경우 '/var/log/solidfire/').
. 이 텍스트 검색:
+
[listing]
----
SIOC is not enabled
----
. 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Plug-in_for_vCenter_server/mNode_Status_shows_as_'Network_Down'_or_'Down'_in_the_mNode_Settings_tab_of_the_Element_Plugin_for_vCenter_(VCP)["이 기사를 참조하십시오"] 사용자의 문제에 해당하는 수정 조치를 확인합니다.

