---
sidebar: sidebar 
permalink: vcp_task_create_manage_initiators.html 
summary: 플러그인을 사용하여 이니시에이터를 생성하고 관리할 수 있습니다. 
keywords: netapp, storage, inititators, vcp, vcenter, element 
---
= 이니시에이터를 생성 및 관리합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이니시에이터는 외부 클라이언트가 클러스터의 볼륨에 액세스할 수 있도록 하며, 클라이언트와 볼륨 간의 통신을 위한 진입점 역할을 합니다.

이니시에이터를 생성, 편집 및 삭제할 수 있으며 친숙한 별칭을 제공하여 관리 및 볼륨 액세스를 간소화할 수 있습니다. 볼륨 액세스 그룹에 이니시에이터를 추가하면 해당 이니시에이터가 그룹의 모든 볼륨에 액세스할 수 있도록 설정합니다.

.옵션
*  an initiator
*  an initiator
*  initiators to an access group
*  an initiator




== 이니시에이터를 생성합니다

iSCSI 또는 파이버 채널 이니시에이터를 생성하고 선택적으로 별칭을 할당할 수 있습니다.

.단계
. NetApp Element 관리 > 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. 이니시에이터 * 하위 탭을 선택합니다.
. 이니시에이터 생성 * 을 선택합니다.
. 단일 이니시에이터를 생성하려면 다음을 따르십시오.
+
.. Create a Single Initiator * 를 선택합니다.
.. IQN/WWPN * 필드에 이니시에이터의 IQN 또는 WWPN을 입력합니다.
+
이니시에이터 IQN의 허용되는 형식은 "iqn.yyyy-mm"입니다. 여기서 y와 m은 숫자, 알파벳 소문자, 마침표, 콜론(":") 또는 대시("-")만 포함해야 하는 숫자 뒤에 오는 텍스트입니다. 형식의 예는 다음과 같습니다.

+
[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----
+
Fibre Channel 이니시에이터 WWPN의 허용되는 형식은 ':AA:BB:CC:dd:11:22:33:44' 또는 'AabBCCdd11223344'입니다. 형식의 예는 다음과 같습니다.

+
[listing]
----
5f:47:ac:c0:5c:74:d4:02
----
.. 별칭 * 필드에 초기자의 이름을 입력합니다.


. 여러 이니시에이터를 생성하려면 다음을 따르십시오.
+
.. 여러 이니시에이터 생성 * 을 선택합니다.
.. 다음 중 하나를 수행합니다.
+
*** vSphere 호스트에서 NetApp Element 클러스터에 정의되지 않은 이니시에이터 값을 검색하려면 * 호스트 검색 * 을 클릭합니다.
*** 텍스트 상자에 IQN 또는 WWPN 목록을 입력하고 * 이니시에이터 추가 * 를 선택합니다.


.. (선택 사항) * Alias * 제목 아래에서 별칭을 추가할 각 항목의 필드를 선택합니다.
.. (선택 사항) 필요에 따라 목록에서 이니시에이터를 제거합니다.


. OK * 를 클릭하여 이니시에이터를 생성합니다.




== 이니시에이터를 편집합니다

기존 이니시에이터의 별칭을 변경하거나 별칭이 없는 경우 추가할 수 있습니다.

.단계
. NetApp Element 관리 > 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. 이니시에이터 * 하위 탭을 선택합니다.
. 편집할 이니시에이터의 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 결과 메뉴에서 * Edit * 를 선택합니다.
. Alias * 필드에 초기자의 새 별칭을 입력합니다.
. 확인 * 을 클릭합니다.




== 액세스 그룹에 이니시에이터를 추가합니다

액세스 그룹에 이니시에이터를 추가하여 CHAP 인증 없이 볼륨 액세스 그룹의 볼륨에 대한 액세스를 허용할 수 있습니다. 볼륨 액세스 그룹에 이니시에이터를 추가하면 해당 이니시에이터는 해당 볼륨 액세스 그룹의 모든 볼륨에 액세스할 수 있습니다.

.단계
. NetApp Element 관리 > 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. 이니시에이터 * 하위 탭을 선택합니다.
. 액세스 그룹에 추가할 이니시에이터에 대한 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 결과 메뉴에서 * 액세스 그룹에 추가 * 를 선택합니다.
. 액세스 그룹에 추가 * 대화 상자의 드롭다운 목록에서 액세스 그룹을 선택합니다.
. 확인 * 을 클릭합니다.




== 이니시에이터를 삭제합니다

더 이상 필요하지 않은 이니시에이터를 삭제할 수 있습니다. 이니시에이터를 삭제하면 연결된 볼륨 액세스 그룹에서 이니시에이터가 제거됩니다. 초기자를 사용하는 모든 연결은 연결이 재설정될 때까지 유효합니다.

.단계
. NetApp Element 관리 > 관리 * 를 선택합니다.
+

NOTE: 두 개 이상의 클러스터가 추가된 경우 탐색 모음에서 작업에 사용할 클러스터가 선택되었는지 확인합니다.

. 이니시에이터 * 하위 탭을 선택합니다.
. 삭제할 이니시에이터에 대한 확인란을 선택합니다.
. 작업 * 을 선택합니다.
. 결과 메뉴에서 * 삭제 * 를 선택합니다.
. 작업을 확인합니다.




== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 문서"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]

